// Supplier Deep Dive — the full Probe42 story for one enriched supplier.
// Reuses the shared chart kit. Opened only for companies we have Probe42 data for.
import type { Entity } from "./types";
import { AreaLine, Columns, HBars, Donut, Card, type Slice } from "./charts";
import { TEAL } from "./lib/palette";
import DETAIL from "@data/clean/probe-detail.json";

/* ---- types (loose; the file is generated by scripts/probe/detail.mjs) ---- */
interface YearRow {
  year: string; revenueCr: number | null; ebitdaCr: number | null; patCr: number | null;
  ebitdaMargin: number | null; netMargin: number | null; roce: number | null;
  receivableDays: number | null; payableDays: number | null; cashConversionCycle: number | null; revenueGrowth: number | null;
}
interface Pair { self: number | null; median: number | null }
interface Detail {
  legalName: string; website: string | null; city: string | null; state: string | null;
  incorporation: string | null; paidUpCr: number | null; lastUpdated: string | null;
  bands: { revenue: string | null; profit: string | null; employees: string | null };
  flags: { gstDelay: boolean; epfDelay: boolean; bureauDefaults: boolean; pendingCases: boolean; severeCases: boolean };
  creditRating: string | null;
  score: { overall: number | null; growth: number | null; profitability: number | null; liquidity: number | null; solvency: number | null; efficiency: number | null };
  latest: Record<string, number | string | null>;
  series: YearRow[];
  vsMedian: Record<string, Pair>;
  peers: { name: string; revenueCr: number; city: string | null; isSelf: boolean }[];
  shareholders: { name: string; pct: number; type: string }[];
  charges: { count: number; sumCr: number | null; topHolder: string | null; topAmountCr: number | null; topDate: string | null };
}
const DETAILS = DETAIL as Record<string, Detail>;

const SH_COLORS = ["#0d9488", "#6366f1", "#f59e0b", "#0ea5e9", "#f43f5e", "#14b8a6", "#8b5cf6"];
const num = (v: unknown): number | null => (typeof v === "number" ? v : null);
const cr = (v: number | null) => (v == null ? "—" : v >= 1000 ? `₹${(v / 1000).toFixed(2)}k Cr` : `₹${v} Cr`);
const days = (v: number | null) => (v == null ? "—" : `${Math.round(v)} d`);
const pct = (v: number | null) => (v == null ? "—" : `${v}%`);

export default function DeepDive({ entity, onClose }: { entity: Entity; onClose: () => void }) {
  const d = entity.cin ? DETAILS[entity.cin] : undefined;
  if (!d) return null;
  const L = d.latest;
  const rev = d.series.map<Slice>((y) => ({ label: y.year, value: y.revenueCr ?? 0, color: TEAL }));
  const ebitdaMargin = d.series.map<Slice>((y) => ({ label: y.year, value: y.ebitdaMargin ?? 0, color: "#6366f1" }));
  const ccc = d.series.map<Slice>((y) => ({ label: y.year, value: y.cashConversionCycle ?? 0, color: "#0ea5e9" }));
  const peerBars = d.peers.map<Slice>((p) => ({ label: p.name.replace(/ (PRIVATE|LIMITED|PVT|LTD)\.?/gi, "").trim(), value: p.revenueCr, color: p.isSelf ? TEAL : "#cbd5e1" }));
  const shares = d.shareholders.map<Slice>((s, i) => ({ label: s.name.replace(/ (PRIVATE|LIMITED|PVT|LTD)\.?/gi, "").trim(), value: s.pct, color: SH_COLORS[i % SH_COLORS.length], sub: s.type }));
  const scoreBars = [
    { label: "Growth", value: d.score.growth ?? 0 },
    { label: "Profitability", value: d.score.profitability ?? 0 },
    { label: "Liquidity", value: d.score.liquidity ?? 0 },
    { label: "Solvency", value: d.score.solvency ?? 0 },
    { label: "Efficiency", value: d.score.efficiency ?? 0 },
  ].map<Slice>((s) => ({ ...s, color: s.value >= 4 ? "#059669" : s.value >= 3 ? "#f59e0b" : "#f43f5e" }));

  // negotiation headline
  const payGap = d.vsMedian.payableDays.median != null && d.vsMedian.payableDays.self != null
    ? Math.round(d.vsMedian.payableDays.median - d.vsMedian.payableDays.self) : null;

  return (
    <div className="fixed inset-0 z-40 overflow-y-auto bg-slate-100">
      {/* header */}
      <div className="sticky top-0 z-10 border-b border-slate-200 bg-white/95 backdrop-blur">
        <div className="mx-auto flex max-w-[1200px] items-center justify-between gap-4 px-4 py-3 sm:px-6">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="truncate text-lg font-bold text-slate-900">{entity.brand}</span>
              <span className="shrink-0 rounded-full bg-teal-50 px-2 py-0.5 text-[11px] font-semibold text-teal-700 ring-1 ring-teal-200">Probe42 · 11-yr filings</span>
            </div>
            <div className="truncate text-xs text-slate-500">
              {d.legalName} · {entity.cin}{d.city ? ` · ${d.city}` : ""}{d.incorporation ? ` · inc. ${d.incorporation.slice(0, 4)}` : ""}
            </div>
          </div>
          <button onClick={onClose} className="shrink-0 rounded-lg bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700">← Back</button>
        </div>
      </div>

      <div className="mx-auto max-w-[1200px] px-4 py-6 sm:px-6">
        {/* KPI strip */}
        <div className="stagger mb-4 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">
          <Kpi label={`Revenue ${L.year ?? ""}`} value={cr(num(L.revenueCr))} tone="ink" />
          <Kpi label="EBITDA margin" value={pct(num(L.ebitdaMargin))} tone="indigo" />
          <Kpi label="RoCE" value={pct(num(L.roce))} tone="teal" />
          <Kpi label="Receivable days" value={days(num(L.receivableDays))} tone="sky" />
          <Kpi label="Payable days" value={days(num(L.payableDays))} tone="amber" />
          <Kpi label="Financial score" value={`${d.score.overall ?? "—"}/5`} tone={(d.score.overall ?? 0) >= 4 ? "emerald" : "amber"} />
        </div>

        {/* negotiation headline */}
        {payGap != null && (
          <div className="mb-5 rounded-2xl bg-gradient-to-r from-teal-600 to-cyan-600 p-5 text-white shadow-sm">
            <div className="text-xs font-semibold uppercase tracking-wide text-teal-100">Negotiation signal</div>
            <div className="mt-1 text-lg font-semibold">
              {payGap > 0
                ? `Pays suppliers in ${d.vsMedian.payableDays.self}d vs peer median ${d.vsMedian.payableDays.median}d — ~${payGap} days of room to extend our terms.`
                : `Already extends payables to ${d.vsMedian.payableDays.self}d (≥ peer median ${d.vsMedian.payableDays.median}d).`}
            </div>
            <div className="mt-1 text-sm text-teal-50">
              RoCE {pct(num(L.roce))} vs peer median {pct(d.vsMedian.roce.median)} · EBITDA margin {pct(num(L.ebitdaMargin))} — {(num(L.roce) ?? 0) > (d.vsMedian.roce.median ?? 0) ? "healthy returns leave room on price." : "returns are near peer levels."}
            </div>
          </div>
        )}

        <div className="stagger grid grid-cols-1 gap-4 lg:grid-cols-3">
          <Card title="Revenue trend" sub="net revenue · ₹ crore" className="lg:col-span-2" accent={TEAL}>
            <AreaLine data={rev} color={TEAL} valueLabel={(v) => `₹${Math.round(v)} Cr`} />
          </Card>

          <Card title="You vs peer median" sub="latest year · lower payable-days gap = room to push" accent="#0ea5e9">
            <div className="space-y-3">
              <Versus label="Payable days" self={d.vsMedian.payableDays.self} median={d.vsMedian.payableDays.median} unit="d" higherSelfBetter />
              <Versus label="Receivable days" self={d.vsMedian.receivableDays.self} median={d.vsMedian.receivableDays.median} unit="d" />
              <Versus label="EBITDA margin" self={d.vsMedian.ebitdaMargin.self} median={d.vsMedian.ebitdaMargin.median} unit="%" higherSelfBetter />
              <Versus label="RoCE" self={d.vsMedian.roce.self} median={d.vsMedian.roce.median} unit="%" higherSelfBetter />
            </div>
          </Card>

          <Card title="EBITDA margin trend" sub="operating profit ÷ revenue · %" accent="#6366f1">
            <Columns data={ebitdaMargin} valueLabel={(v) => `${v}%`} />
          </Card>

          <Card title="Cash conversion cycle" sub="days of cash tied up · lower is better" accent="#0ea5e9">
            <AreaLine data={ccc} color="#0ea5e9" valueLabel={(v) => `${Math.round(v)}d`} area={false} />
          </Card>

          <Card title="Financial health score" sub="Probe42 · out of 5" accent="#059669">
            <HBars data={scoreBars} valueLabel={(v) => `${v}/5`} />
          </Card>

          <Card title="Peers by revenue" sub="5 closest peers · you highlighted · ₹ crore" className="lg:col-span-2" accent={TEAL}>
            <HBars data={peerBars} valueLabel={(v) => `₹${Math.round(v)} Cr`} />
          </Card>

          <Card title="Shareholding (>5%)" sub="latest filing" accent="#6366f1">
            {shares.length ? <Donut data={shares} centerValue={`${shares.length}`} centerLabel="holders" unit="%" /> : <Empty />}
          </Card>

          <Card title="Working capital" sub={`${L.year ?? ""} · ₹ crore on the balance sheet`} accent="#14b8a6">
            <div className="grid grid-cols-3 gap-3">
              <WC label="Receivables" value={cr(num(L.receivablesCr))} sub={`${days(num(L.receivableDays))} outstanding`} />
              <WC label="Payables" value={cr(num(L.payablesCr))} sub={`${days(num(L.payableDays))} to pay`} />
              <WC label="Inventory" value={cr(num(L.inventoryCr))} sub={`${days(num(L.inventoryDays))} of stock`} />
            </div>
            <div className="mt-4 flex gap-4 text-xs text-slate-500">
              <span>Current ratio <b className="font-mono text-slate-800">{num(L.currentRatio) ?? "—"}</b></span>
              <span>Debt / equity <b className="font-mono text-slate-800">{num(L.debtToEquity) ?? "—"}</b></span>
            </div>
          </Card>

          <Card title="Risk & compliance" sub="flags, rating & secured lenders" accent="#f43f5e">
            <div className="mb-3 flex flex-wrap gap-2">
              <Flag on={d.flags.gstDelay} label="GST filing delay" />
              <Flag on={d.flags.epfDelay} label="EPF payment delay" />
              <Flag on={d.flags.bureauDefaults} label="Bureau default" />
              <Flag on={d.flags.pendingCases} label="Pending case" />
            </div>
            <dl className="space-y-1.5 text-sm">
              <Row k="Credit rating" v={d.creditRating ?? "Not rated"} />
              <Row k="Secured charges" v={d.charges.count ? `${d.charges.count} · ${cr(d.charges.sumCr)}` : "None"} />
              {d.charges.topHolder && <Row k="Main lender" v={`${d.charges.topHolder} (${cr(d.charges.topAmountCr)})`} />}
              <Row k="Paid-up capital" v={cr(d.paidUpCr)} />
            </dl>
          </Card>
        </div>

        <p className="mt-5 text-xs text-slate-400">
          Source: Probe42 comprehensive filings (MCA){d.lastUpdated ? ` · data as of ${d.lastUpdated.slice(0, 10)}` : ""}. One of 3 suppliers enabled — the rest unlock once Probe42 is on the paid plan.
        </p>
      </div>
    </div>
  );
}

/* ---------------------------------------------------------------- helpers */

function Kpi({ label, value, tone }: { label: string; value: string; tone: string }) {
  const c: Record<string, string> = { ink: "text-slate-900", teal: "text-teal-600", indigo: "text-indigo-600", sky: "text-sky-600", amber: "text-amber-600", emerald: "text-emerald-600" };
  return (
    <div className="rounded-2xl bg-white p-3.5 shadow-sm ring-1 ring-slate-200">
      <div className="text-[11px] font-medium uppercase tracking-wide text-slate-500">{label}</div>
      <div className={`mt-1 text-xl font-semibold tabular-nums ${c[tone] ?? c.ink}`}>{value}</div>
    </div>
  );
}

function Versus({ label, self, median, unit, higherSelfBetter }: { label: string; self: number | null; median: number | null; unit: string; higherSelfBetter?: boolean }) {
  const max = Math.max(1, self ?? 0, median ?? 0);
  const better = self != null && median != null && (higherSelfBetter ? self >= median : self <= median);
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-xs">
        <span className="text-slate-600">{label}</span>
        <span className={`font-mono font-semibold ${better ? "text-emerald-600" : "text-slate-500"}`}>
          {self ?? "—"}{unit} <span className="text-slate-400">vs {median ?? "—"}{unit}</span>
        </span>
      </div>
      <div className="relative h-3 rounded-full bg-slate-100">
        <div className="absolute inset-y-0 rounded-full bg-teal-500" style={{ width: `${((self ?? 0) / max) * 100}%` }} />
        <div className="absolute inset-y-0 w-0.5 bg-slate-500" style={{ left: `${((median ?? 0) / max) * 100}%` }} title={`peer median ${median}${unit}`} />
      </div>
    </div>
  );
}

function WC({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
      <div className="text-xs text-slate-500">{label}</div>
      <div className="mt-0.5 font-mono text-sm font-semibold text-slate-900">{value}</div>
      <div className="text-[11px] text-slate-400">{sub}</div>
    </div>
  );
}

function Flag({ on, label }: { on: boolean; label: string }) {
  return (
    <span className={`rounded-full px-2 py-0.5 text-xs font-medium ring-1 ${on ? "bg-rose-50 text-rose-700 ring-rose-200" : "bg-emerald-50 text-emerald-700 ring-emerald-200"}`}>
      {on ? "⚠ " : "✓ "}{label}
    </span>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex justify-between gap-4 border-b border-slate-100 pb-1.5">
      <dt className="text-slate-500">{k}</dt>
      <dd className="text-right text-slate-800">{v}</dd>
    </div>
  );
}

function Empty() {
  return <div className="py-6 text-center text-sm text-slate-400">No disclosed holders &gt;5%.</div>;
}
