// Supplier Deep Dive — the COMPLETE Probe42 story for one enriched supplier,
// organised into tabs so nothing is left out but you're never buried in scroll.
// The lever engine's output leads; every historical number is a trend.
import { Fragment, useMemo, useState } from "react";
import type { Entity } from "./types";
import { AreaLine, HBars, Donut, MultiLine, Card, type Slice } from "./charts";
import { TEAL } from "./lib/palette";
import { fullName, titleCase } from "./lib/format";
import { newsOf, type SupplierNews } from "./news";
import DETAIL from "@data/clean/probe-detail.json";
import ENTITIES from "@data/clean/entities.json";

/* ---- types (loose; generated by scripts/probe/detail.mjs) ---- */
type Ratios = Record<string, number | null>;
interface FinRow {
  fy: string; revenue: number | null; pat: number | null; ebitda: number | null;
  materialCost?: number | null; purchases?: number | null; employeeCost?: number | null; otherExpense?: number | null;
  otherIncome?: number | null; depreciation?: number | null; ebit?: number | null; interest?: number | null; pbt?: number | null; tax?: number | null;
  bs: Record<string, number | null>; cf: Record<string, number | null>; r: Ratios;
}
interface Evidence { label: string; value: string; tab: string }
interface Lever { tone: "opportunity" | "watch" | "risk"; strength: number; title: string; detail: string; evidence?: Evidence[] }
interface CostMix { material: number | null; employee: number | null; other: number | null; deprec: number | null }
interface AdvYear { fy: string; roe: number | null; netMargin: number | null; assetTurn: number | null; equityMult: number | null; taxBurden: number | null; intBurden: number | null; opMargin: number | null; fcf: number | null; accruals: number | null; workingCapital: number | null; costMix: CostMix | null }
interface Advanced {
  perYear: AdvYear[]; fscore: number | null; fChecks: { ok: boolean; label: string }[]; z: number | null; zZone: "safe" | "grey" | "distress" | null;
  opLeverage: number | null; fcfLatest: number | null; accrualsLatest: number | null;
  dupont: { netMargin: number | null; assetTurn: number | null; equityMult: number | null; roe: number | null; taxBurden: number | null; intBurden: number | null; opMargin: number | null } | null;
}
interface Detail {
  cin: string; legalName: string; description: string | null; website: string | null; city: string | null; state: string | null;
  incorporation: string | null; classification: string | null; status: string | null; industry: string | null; segment: string | null; segments: string[];
  activities: { desc: string; pct: number | null }[]; paidUpCr: number | null; authorizedCr: number | null; lastAgm: string | null; lastFiling: string | null;
  lastUpdated: string | null; yearsCovered: number | null;
  score: Record<string, number | null>; bands: { revenue: string | null; profit: string | null; employees: string | null };
  flags: Record<string, boolean>;
  creditRating: { agency: string | null; date: string | null; grade: string | null; gradeText: string | null; ratedAmountCr: number | null; outlook?: string | null; facilities: { loan: string | null; rating: string | null; amountCr: number | null }[]; flags: Record<string, boolean> } | null;
  nameHistory: string[];
  forex: { fy: string; earnCr: number | null; spendCr: number | null } | null;
  agedReceivables: { fy: string; amountCr: number | null } | null;
  auditor: { current: string | null; signedBy: string | null; changes: number; firms: string[]; anyAdverse: boolean; adverseYears: string[]; adverseRecent: boolean; adverseSustained: boolean; latestFy: string | null } | null;
  revenueMix: { fy: string; manufacturedCr: number | null; tradedCr: number | null; servicesCr: number | null; manufacturedPct: number | null; tradedPct: number | null; servicesPct: number | null; exportCr: number | null; exportPct: number | null; kind: string } | null;
  activityGroup: string | null;
  gstNature: string[];
  managerialPay: { fy: string; amountCr: number | null; pctOfProfit: number | null } | null;
  proposedDividend: boolean;
  capexWip: { fy: string; amountCr: number | null; pctOfFixedAssets: number | null } | null;
  borrowingCost: { ratePct: number | null } | null;
  powerCost: { fy: string; amountCr: number | null; pctOfRevenue: number | null } | null;
  assetAge: { fy: string; grossCr: number | null; netCr: number | null; depreciatedPct: number | null } | null;
  latest: Record<string, number | string | null>;
  fin: FinRow[];
  employees: { latest: number | null; yearly: { fy: string; count: number }[]; monthly: { month: string; count: number; onTime: boolean }[] };
  peers: { industry: string | null; segment: string | null; sampleSize: number | null; named: { name: string; revenueCr: number; city: string | null; isSelf?: boolean }[]; benchmarks: { year: string; peers: number | null; self: Ratios; median: Ratios }[] };
  vsMedian: { self: Ratios; median: Ratios };
  ownership: { promoterPct: number | null; publicPct: number | null };
  shareholders: { name: string; pct: number; type: string }[];
  directors: { name: string; designation: string | null; since: string | null; age: number | null; otherCount: number; others: string[]; ownPct: number | null }[];
  charges: { count: number; sumCr: number | null; everCreated?: number; satisfied?: number; list: { holder: string; amountCr: number | null; date: string; type: string }[] };
  legal: { count: number; high: number; medium: number; against: number; list: { court: string; date: string; status: string; type: string; category: string; severity: string; counterparty: string }[] };
  financialDisputes: { count: number; receivable: number; payable: number; list: { direction: string; type: string | null; verdict: string | null; court: string | null; counterparty: string | null; caseNo: string | null; amountCr: number | null; date: string | null }[] };
  group: Record<string, { name: string; pct: number | null; city: string | null }[]>;
  relatedParty: { year: string | null; count: number; totalCr: number | null; top: { name: string; relationship: string; kind: string; amountCr: number | null }[] };
  gst: { list: { gstin: string; state: string; status: string; timeliness: string }[]; onTime: number; total: number };
  allotments: { date: string; type: string; instrument: string; amountCr: number | null }[];
  paymentBehaviour: { hasData: boolean; latestPeriod: string | null; latestDueLakh: number | null; worstPeriod: string | null; worstLakh: number | null; delayedSuppliers: string[]; trend: { period: string; lakh: number | null }[] };
  levers: Lever[];
  advanced?: Advanced;
}
const DETAILS = DETAIL as unknown as Record<string, Detail>;

/* ---- financial-health score (0-100) + category alternatives (#2) ----
   Blends everything we hold into one comparable number so we can rank a supplier
   against the others we track in its category and, when it's weak, name healthier
   backups to qualify as a second source. */
export function healthScore(d: Detail): number {
  let s = 50;
  const a = d.advanced;
  if (a?.fscore != null) s += (a.fscore - 4.5) * 4;               // Piotroski 0-9 → ±18
  if (d.score?.overall != null) s += ((d.score.overall as number) - 5) * 3; // Probe 0-10 → ±15
  if (a?.zZone === "distress") s -= 15; else if (a?.zZone === "safe") s += 4;
  const rt = d.creditRating;
  if (rt) { if (rt.flags.isDefault) s -= 25; else if (rt.flags.subInvestmentGrade) s -= 12; else if (rt.flags.inc) s -= 8; else if (rt.flags.strong) s += 10; }
  s -= d.levers.filter((l) => l.tone === "risk").length * 4;
  return Math.max(1, Math.min(100, Math.round(s)));
}
type EnrichedRef = { cin: string; brand: string; legalName: string | null; category: string; health: number };
const ALL_ENRICHED: EnrichedRef[] = ((ENTITIES as { entities: { cin: string | null; brand: string; legalName: string | null; category: string }[] }).entities)
  .filter((e) => e.cin && DETAILS[e.cin])
  .map((e) => ({ cin: e.cin as string, brand: e.brand, legalName: e.legalName, category: e.category, health: healthScore(DETAILS[e.cin as string]) }));

/** True when we hold a Probe42 comprehensive report for this company. */
export function hasDeepDive(cin?: string | null): boolean { return !!(cin && DETAILS[cin]); }
/** The lever-engine output for a company (empty if no Probe42 report). */
export function probeLevers(cin?: string | null): Lever[] { return (cin && DETAILS[cin]?.levers) || []; }
/** Blended 0-100 financial-health score for an enriched supplier (null if not enriched). */
export function supplierHealth(cin?: string | null): number | null { return cin && DETAILS[cin] ? healthScore(DETAILS[cin]) : null; }
export type ProbeLever = Lever;

/* ---- palette + formatters ---- */
const C = { teal: TEAL, indigo: "#6366f1", sky: "#0ea5e9", amber: "#f59e0b", rose: "#f43f5e", violet: "#8b5cf6", emerald: "#059669", slate: "#94a3b8" };
const SH_COLORS = [C.teal, C.indigo, C.amber, C.sky, C.rose, C.violet, C.emerald];
const n = (v: unknown): number | null => (typeof v === "number" && Number.isFinite(v) ? v : null);
const cr = (v: number | null) => (v == null ? "—" : Math.abs(v) >= 1000 ? `₹${(v / 1000).toFixed(2)}k Cr` : `₹${v} Cr`);
const pct = (v: number | null) => (v == null ? "—" : `${v}%`);
const days = (v: number | null) => (v == null ? "—" : `${Math.round(v)} d`);
const xN = (v: number | null) => (v == null ? "—" : `${v}x`);
const lk = (v: number | null) => (v == null ? "—" : v >= 100 ? `₹${(v / 100).toFixed(1)} Cr` : `₹${v} L`);

const TABS = [
  { key: "levers", label: "💡 Levers" },
  { key: "financials", label: "📈 Financials & trends" },
  { key: "peers", label: "🏁 Peers" },
  { key: "owners", label: "🏛️ Owners & people" },
  { key: "risk", label: "🚩 Risk & legal" },
  { key: "news", label: "📰 News" },
  { key: "about", label: "ℹ️ About" },
] as const;
type TabKey = (typeof TABS)[number]["key"];

export default function DeepDive({ entity, onClose, supplies }: { entity: Entity; onClose: () => void; supplies?: string[] }) {
  const d = entity.cin ? DETAILS[entity.cin] : undefined;
  const [tab, setTab] = useState<TabKey>("levers");
  if (!d) return null;
  const L = d.latest;
  const opps = d.levers.filter((l) => l.tone === "opportunity").length;
  const news = newsOf(entity.folder);
  const newsCount = news ? news.news.length + news.signals.length : 0;
  // #2 — where this supplier stands vs the others we track in its category
  const catAll = ALL_ENRICHED.filter((x) => x.category === entity.category).sort((a, b) => b.health - a.health);
  const selfHealth = healthScore(d);
  const alt = { selfHealth, category: entity.category, count: catAll.length, rank: catAll.findIndex((x) => x.cin === entity.cin) + 1, better: catAll.filter((x) => x.cin !== entity.cin && x.health > selfHealth + 8).slice(0, 3) };

  return (
    <div className="fixed inset-0 z-40 overflow-y-auto bg-slate-100">
      {/* header */}
      <div className="sticky top-0 z-10 border-b border-slate-200 bg-white/95 backdrop-blur">
        <div className="mx-auto max-w-[1680px] px-4 py-3 sm:px-6">
          {/* Identity line: the name is the headline, then only what a buyer needs
              to place the company — where it is, and what it sells us. The CIN,
              the "Probe42 · N-yr filings" badge, the listing status and the
              former-names trail all moved to the About tab; they were noise here. */}
          <div className="flex items-start justify-between gap-4">
            <div className="min-w-0">
              <h1 className="truncate text-2xl font-bold leading-tight tracking-tight text-slate-900" title={fullName(d.legalName, entity.brand)}>{fullName(d.legalName, entity.brand)}</h1>
              <div className="mt-1 flex flex-wrap items-center gap-x-2.5 gap-y-1 text-sm text-slate-500">
                {d.city && <span className="inline-flex items-center gap-1">📍 {titleCase(d.city)}</span>}
                {supplies && supplies.length > 0 && (
                  <span className="inline-flex min-w-0 items-center gap-1" title={supplies.join(", ")}>
                    <span className="text-slate-300">·</span> supplies <span className="truncate font-medium text-slate-700">{supplies[0]}{supplies.length > 1 ? ` +${supplies.length - 1} more` : ""}</span>
                  </span>
                )}
              </div>
            </div>
            <button onClick={onClose} className="shrink-0 rounded-lg bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700">← Back</button>
          </div>
          {/* KPI strip */}
          <div className="mt-4 grid grid-cols-3 gap-2 md:grid-cols-6">
            <Kpi label={`Revenue ${L.year ?? ""}`} value={cr(n(L.revenue))} tone="ink" />
            <Kpi label="EBITDA margin" value={pct(n(L.ebitdaMargin))} tone="indigo" />
            <Kpi label="RoCE" value={pct(n(L.roce))} tone="teal" />
            <Kpi label="Collects / Pays" value={`${days(n(L.debtorDays))} / ${days(n(L.payableDays))}`} tone="sky" />
            <Kpi label="Debt / equity" value={n(L.debtEquity) ?? "—"} tone="amber" />
            <Kpi label="Financial score" value={`${d.score.overall ?? "—"}/10`} tone={(d.score.overall ?? 0) >= 7 ? "emerald" : (d.score.overall ?? 0) >= 4 ? "amber" : "rose"} />
          </div>
          {/* tabs */}
          <div className="mt-3 flex gap-1 overflow-x-auto">
            {TABS.map((t) => (
              <button key={t.key} onClick={() => setTab(t.key)}
                className={`shrink-0 whitespace-nowrap rounded-lg px-3 py-1.5 text-sm font-semibold transition ${tab === t.key ? "bg-teal-600 text-white shadow-sm" : "text-slate-500 hover:bg-slate-100 hover:text-slate-800"}`}>
                {t.label}{t.key === "levers" ? ` · ${d.levers.length}` : t.key === "news" && newsCount ? ` · ${newsCount}` : ""}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-[1680px] px-4 py-6 sm:px-6">
        {tab === "levers" && <LeversTab d={d} opps={opps} onGoto={(t) => setTab(t as TabKey)} alt={alt} />}
        {tab === "financials" && <FinancialsTab d={d} />}
        {tab === "peers" && <PeersTab d={d} />}
        {tab === "owners" && <OwnersTab d={d} />}
        {tab === "risk" && <RiskTab d={d} />}
        {tab === "news" && <NewsTab news={news} brand={entity.brand} />}
        {tab === "about" && <AboutTab d={d} />}
        <p className="mt-5 text-xs text-slate-400">
          Source: MCA filings via Probe42{d.lastUpdated ? ` · as of ${d.lastUpdated.slice(0, 10)}` : ""} · {d.yearsCovered ?? d.fin.length} years of accounts.
        </p>
      </div>
    </div>
  );
}

/* ===================================================================== LEVERS */
const TAB_META: Record<string, { name: string; cls: string }> = {
  financials: { name: "Financials", cls: "bg-teal-100 text-teal-700 hover:bg-teal-200" },
  peers: { name: "Peers", cls: "bg-sky-100 text-sky-700 hover:bg-sky-200" },
  owners: { name: "Owners", cls: "bg-violet-100 text-violet-700 hover:bg-violet-200" },
  risk: { name: "Risk & legal", cls: "bg-rose-100 text-rose-700 hover:bg-rose-200" },
};
type AltInfo = { selfHealth: number; category: string; count: number; rank: number; better: EnrichedRef[] };
function AlternativesCard({ alt }: { alt: AltInfo }) {
  if (alt.count < 2) return null; // need at least one category peer to compare
  const weak = alt.selfHealth < 55;
  const dot = (h: number) => (h >= 65 ? "bg-emerald-500" : h >= 50 ? "bg-amber-500" : "bg-rose-500");
  return (
    <div className={`mb-4 rounded-2xl p-4 ring-1 ${weak ? "bg-rose-50 ring-rose-200" : "bg-slate-50 ring-slate-200"}`}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-sm font-bold text-slate-800">{weak ? "⚠ Line up a backup source" : "🔁 Alternatives in this category"}</span>
        <span className="inline-flex items-center gap-1.5 rounded-full bg-white px-2 py-0.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><span className={`h-2 w-2 rounded-full ${dot(alt.selfHealth)}`} />health {alt.selfHealth}/100 · #{alt.rank} of {alt.count} {alt.category}s we track</span>
      </div>
      {alt.better.length > 0 ? (
        <>
          <div className="mt-2 text-xs text-slate-600">{weak ? "This vendor reads weaker than others we track — healthier options to qualify as a second source:" : "Healthier vendors in the same category, if you want a backup:"}</div>
          <div className="mt-2 flex flex-wrap gap-2">
            {alt.better.map((p) => <span key={p.cin} className="inline-flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-1 text-xs font-medium text-slate-700 ring-1 ring-slate-200"><span className={`h-2 w-2 rounded-full ${dot(p.health)}`} />{fullName(p.legalName, p.brand)} · {p.health}/100</span>)}
          </div>
        </>
      ) : <div className="mt-1 text-xs text-slate-500">✓ One of the healthiest {alt.category} suppliers we track — no clearly stronger alternative on file.</div>}
    </div>
  );
}
function LeversTab({ d, opps, onGoto, alt }: { d: Detail; opps: number; onGoto: (t: string) => void; alt: AltInfo }) {
  const [open, setOpen] = useState<string | null>(null);
  const watches = d.levers.filter((l) => l.tone === "watch").length;
  const risks = d.levers.filter((l) => l.tone === "risk").length;
  const groups: { tone: Lever["tone"]; title: string; ring: string; bg: string; text: string; emoji: string }[] = [
    { tone: "opportunity", title: "Plays for us", ring: "ring-emerald-200", bg: "bg-emerald-50", text: "text-emerald-800", emoji: "✅" },
    { tone: "watch", title: "Worth watching", ring: "ring-amber-200", bg: "bg-amber-50", text: "text-amber-800", emoji: "👀" },
    { tone: "risk", title: "Risks / cautions", ring: "ring-rose-200", bg: "bg-rose-50", text: "text-rose-800", emoji: "🚩" },
  ];
  return (
    <div>
      <div className="mb-4 rounded-2xl bg-gradient-to-r from-teal-600 to-cyan-600 p-4 text-white shadow-sm">
        <div className="text-xs font-semibold uppercase tracking-wide text-teal-100">Negotiation-lever engine</div>
        {/* split the non-opportunity levers the same way the columns below do —
            lumping watch + risk into one "to watch" number contradicted them. */}
        <div className="mt-0.5 text-lg font-semibold">
          {opps} play{opps !== 1 ? "s" : ""} in our favour
          {watches > 0 && <> · {watches} to watch</>}
          {risks > 0 && <> · {risks} risk{risks !== 1 ? "s" : ""}</>}
          <span className="font-normal text-teal-100/90"> — read straight off {d.yearsCovered}&nbsp;years of their filings.</span>
        </div>
        <div className="mt-1 text-xs text-teal-100/90">Click any lever to see the exact numbers behind it.</div>
      </div>
      <AlternativesCard alt={alt} />
      <div className="grid items-start gap-4 lg:grid-cols-3">
        {groups.map((g) => {
          const items = d.levers.filter((l) => l.tone === g.tone);
          return (
            <div key={g.tone}>
              <div className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-700">{g.emoji} {g.title} <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-500">{items.length}</span></div>
              <div className="space-y-2.5">
                {items.length === 0 && <div className="rounded-xl bg-white p-3 text-sm text-slate-400 ring-1 ring-slate-200">None.</div>}
                {items.map((lv, i) => {
                  const key = g.tone + i, isOpen = open === key, hasEv = (lv.evidence?.length ?? 0) > 0;
                  return (
                    <div key={i} className={`overflow-hidden rounded-xl ${g.bg} ring-1 ${g.ring} transition ${isOpen ? "shadow-md" : ""}`}>
                      <button onClick={() => hasEv && setOpen(isOpen ? null : key)} className={`flex w-full items-start justify-between gap-2 p-3.5 text-left ${hasEv ? "hover:bg-white/30" : "cursor-default"}`}>
                        <div className="min-w-0">
                          <div className={`text-sm font-semibold ${g.text}`}>{lv.title}</div>
                          <p className="mt-1 text-xs leading-relaxed text-slate-600">{lv.detail}</p>
                        </div>
                        <div className="flex shrink-0 flex-col items-end gap-1">
                          <span className="text-xs" title={`strength ${lv.strength}/3`}>{"●".repeat(lv.strength)}<span className="text-slate-300">{"●".repeat(3 - lv.strength)}</span></span>
                          {hasEv && <span className="whitespace-nowrap text-[10px] font-semibold text-slate-400">{isOpen ? "hide ▲" : "why? ▾"}</span>}
                        </div>
                      </button>
                      {isOpen && hasEv && (
                        <div className="border-t border-white/70 bg-white/60 px-3.5 py-2.5">
                          <div className="mb-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">The numbers behind it — tap a source to open that tab</div>
                          <div className="flex flex-wrap gap-1.5">
                            {lv.evidence!.map((e, j) => {
                              const tm = TAB_META[e.tab] ?? { name: e.tab, cls: "bg-slate-100 text-slate-600 hover:bg-slate-200" };
                              return (
                                <span key={j} className="inline-flex items-center gap-1.5 rounded-lg bg-white px-2 py-1 text-xs ring-1 ring-slate-200">
                                  <span className="text-slate-500">{e.label}</span>
                                  <span className="font-semibold text-slate-900">{e.value}</span>
                                  <button onClick={() => onGoto(e.tab)} title={`Open ${tm.name}`} className={`rounded px-1.5 py-0.5 text-[9px] font-semibold transition ${tm.cls}`}>{tm.name} →</button>
                                </span>
                              );
                            })}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ============================================================= FINANCIALS/TRENDS */
// One consolidated chart driven by a multi-check dropdown — tick any metrics to
// overlay them, instead of a wall of separate charts. Metrics are grouped by unit
// so same-unit picks (all margins, all days, all ₹) share a clean axis.
type Metric = { key: string; label: string; group: string; unit: string; color: string; get: (f: FinRow) => number | null };
const UNIT_FMT: Record<string, (v: number) => string> = { "₹cr": (v) => `₹${Math.round(v)} Cr`, "%": (v) => `${v}%`, d: (v) => `${Math.round(v)} d`, ratio: (v) => v.toFixed(2), ppl: (v) => `${Math.round(v)}` };
const PAL = ["#0d9488", "#6366f1", "#0ea5e9", "#f59e0b", "#f43f5e", "#8b5cf6", "#059669", "#0891b2", "#e11d48", "#7c3aed"];
const EXP_METRICS: Metric[] = [
  { key: "revenue", label: "Revenue", group: "Income (₹ cr)", unit: "₹cr", color: PAL[0], get: (f) => f.revenue },
  { key: "ebitda", label: "EBITDA", group: "Income (₹ cr)", unit: "₹cr", color: PAL[1], get: (f) => f.ebitda },
  { key: "pat", label: "Profit after tax", group: "Income (₹ cr)", unit: "₹cr", color: PAL[2], get: (f) => f.pat },
  { key: "materialCost", label: "Material cost", group: "Income (₹ cr)", unit: "₹cr", color: PAL[8], get: (f) => f.materialCost ?? null },
  { key: "employeeCost", label: "Employee cost", group: "Income (₹ cr)", unit: "₹cr", color: PAL[9], get: (f) => f.employeeCost ?? null },
  { key: "equity", label: "Equity / net worth", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[3], get: (f) => f.bs.equity },
  { key: "debt", label: "Total debt", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[4], get: (f) => f.bs.debt },
  { key: "assets", label: "Total assets", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[5], get: (f) => f.bs.totalAssets },
  { key: "inv", label: "Inventory", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[8], get: (f) => f.bs.inventory },
  { key: "recv", label: "Receivables", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[2], get: (f) => f.bs.receivables },
  { key: "cash", label: "Cash", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[6], get: (f) => f.bs.cash },
  { key: "pay", label: "Payables", group: "Balance sheet (₹ cr)", unit: "₹cr", color: PAL[4], get: (f) => f.bs.payables },
  { key: "ocf", label: "Operating cash flow", group: "Cash flow (₹ cr)", unit: "₹cr", color: PAL[6], get: (f) => f.cf.operating },
  { key: "icf", label: "Investing cash flow", group: "Cash flow (₹ cr)", unit: "₹cr", color: PAL[4], get: (f) => f.cf.investing },
  { key: "fcf", label: "Financing cash flow", group: "Cash flow (₹ cr)", unit: "₹cr", color: PAL[5], get: (f) => f.cf.financing },
  { key: "ebitdaMargin", label: "EBITDA margin", group: "Margins & returns (%)", unit: "%", color: PAL[1], get: (f) => f.r.ebitdaMargin },
  { key: "netMargin", label: "Net margin", group: "Margins & returns (%)", unit: "%", color: PAL[0], get: (f) => f.r.netMargin },
  { key: "grossMargin", label: "Gross margin", group: "Margins & returns (%)", unit: "%", color: PAL[2], get: (f) => f.r.grossMargin },
  { key: "roce", label: "RoCE", group: "Margins & returns (%)", unit: "%", color: PAL[3], get: (f) => f.r.roce },
  { key: "roe", label: "RoE", group: "Margins & returns (%)", unit: "%", color: PAL[5], get: (f) => f.r.roe },
  { key: "dso", label: "Collects (DSO)", group: "Working-capital days", unit: "d", color: PAL[2], get: (f) => f.r.debtorDays },
  { key: "dpo", label: "Pays (DPO)", group: "Working-capital days", unit: "d", color: PAL[3], get: (f) => f.r.payableDays },
  { key: "invDays", label: "Inventory days", group: "Working-capital days", unit: "d", color: PAL[5], get: (f) => f.r.inventoryDays },
  { key: "ccc", label: "Cash cycle", group: "Working-capital days", unit: "d", color: PAL[4], get: (f) => f.r.cashConversion },
  { key: "de", label: "Debt / equity", group: "Ratios", unit: "ratio", color: PAL[4], get: (f) => f.r.debtEquity },
  { key: "current", label: "Current ratio", group: "Ratios", unit: "ratio", color: PAL[0], get: (f) => f.r.currentRatio },
  { key: "icov", label: "Interest cover", group: "Ratios", unit: "ratio", color: PAL[1], get: (f) => f.r.interestCover },
];
function TrendExplorer({ fin, empByFy }: { fin: FinRow[]; empByFy: Map<string, number> }) {
  const metrics = useMemo(() => [...EXP_METRICS, { key: "hc", label: "Headcount", group: "People", unit: "ppl", color: PAL[7], get: (f: FinRow) => empByFy.get(f.fy) ?? null }], [empByFy]);
  const [sel, setSel] = useState<Set<string>>(new Set(["revenue", "pat"]));
  const [open, setOpen] = useState(false);
  const chosen = metrics.filter((m) => sel.has(m.key));
  const units = new Set(chosen.map((m) => m.unit));
  const fmt = units.size === 1 ? (UNIT_FMT[[...units][0]] ?? ((v: number) => `${v}`)) : (v: number) => `${v}`;
  const yrs = fin.map((f) => f.fy);
  const series = chosen.map((m) => ({ name: m.label, color: m.color, points: fin.map(m.get) }));
  const groups = [...new Set(metrics.map((m) => m.group))];
  const toggle = (k: string) => setSel((s) => { const nx = new Set(s); nx.has(k) ? nx.delete(k) : nx.add(k); return nx; });
  return (
    <Card title="Trend explorer" sub="tick any metrics to overlay them · picks of the same unit (%, days, ₹) read cleanest" accent={TEAL}>
      <div className="relative mb-2">
        <button onClick={() => setOpen((o) => !o)} className="inline-flex items-center gap-2 rounded-lg bg-white px-3 py-1.5 text-sm font-semibold text-slate-700 ring-1 ring-slate-300 hover:ring-teal-400">
          ➕ Choose metrics <span className="rounded-full bg-teal-100 px-1.5 text-xs text-teal-700">{chosen.length}</span> <span className="text-slate-400">▾</span>
        </button>
        {open && (
          <>
            <button className="fixed inset-0 z-10 cursor-default" onClick={() => setOpen(false)} aria-label="close" />
            <div className="absolute left-0 z-20 mt-1 max-h-[22rem] w-72 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl">
              {groups.map((g) => (
                <div key={g} className="mb-1">
                  <div className="px-2 py-1 text-[11px] font-bold uppercase tracking-wide text-slate-400">{g}</div>
                  {metrics.filter((m) => m.group === g).map((m) => (
                    <label key={m.key} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-1 text-sm hover:bg-slate-50">
                      <input type="checkbox" checked={sel.has(m.key)} onChange={() => toggle(m.key)} className="h-4 w-4 rounded border-slate-300 text-teal-600 focus:ring-teal-400" />
                      <span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: m.color }} />
                      <span className="text-slate-700">{m.label}</span>
                    </label>
                  ))}
                </div>
              ))}
            </div>
          </>
        )}
        <div className="mt-2 flex flex-wrap gap-1.5">
          {chosen.map((m) => (
            <button key={m.key} onClick={() => toggle(m.key)} className="inline-flex items-center gap-1 rounded-md bg-slate-100 px-2 py-0.5 text-xs text-slate-600 hover:bg-rose-50 hover:text-rose-600">
              <span className="h-2 w-2 rounded-sm" style={{ background: m.color }} />{m.label}<span className="text-slate-400">✕</span>
            </button>
          ))}
        </div>
      </div>
      {chosen.length ? <MultiLine xLabels={yrs} series={series} valueLabel={fmt} height={340} /> : <div className="py-16 text-center text-sm text-slate-400">Tick a metric above to plot it.</div>}
    </Card>
  );
}
/* ===================================================================== NEWS */
const SIG_TONE: Record<string, string> = {
  "Ownership change": "border-violet-400 bg-violet-50",
  "Capex / expansion": "border-emerald-400 bg-emerald-50",
  "Market position": "border-slate-300 bg-slate-50",
  Legal: "border-rose-400 bg-rose-50",
  Regulatory: "border-amber-400 bg-amber-50",
  Distress: "border-rose-400 bg-rose-50",
};
function NewsTab({ news, brand }: { news: SupplierNews | null; brand: string }) {
  if (!news) return (
    <div className="rounded-2xl bg-white p-12 text-center ring-1 ring-slate-200">
      <div className="text-4xl">📰</div>
      <div className="mt-3 text-base font-semibold text-slate-700">No significant recent news</div>
      <div className="mx-auto mt-1 max-w-md text-sm text-slate-400">{brand} keeps a low public profile — suppliers rarely generate press. For this one, the leverage lives in the financials, not the headlines.</div>
    </div>
  );
  return (
    <div className="space-y-4">
      {news.signals.length > 0 && (
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {news.signals.map((s, i) => (
            <a key={i} href={s.url} target="_blank" rel="noreferrer" className={`block rounded-xl border-l-4 p-3.5 shadow-sm ring-1 ring-slate-200/60 transition hover:shadow-md ${SIG_TONE[s.type] ?? "border-slate-300 bg-slate-50"}`}>
              <div className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{s.type}</div>
              <p className="mt-1 text-sm leading-snug text-slate-700">{s.oneLine}</p>
              <div className="mt-1.5 text-[11px] font-medium text-slate-400">{s.source} ↗</div>
            </a>
          ))}
        </div>
      )}
      {news.news.length > 0 ? (
        <Card title="📰 In the news" sub={news.summary} accent={C.slate}>
          <div className="divide-y divide-slate-100">
            {news.news.map((it, i) => (
              <a key={i} href={it.url} target="_blank" rel="noreferrer" className="block py-3 transition hover:bg-slate-50/70">
                <div className="flex items-baseline gap-2.5">
                  <span className="shrink-0 rounded bg-slate-100 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-slate-500">{it.date}</span>
                  <span className="text-sm font-bold leading-snug text-slate-900">{it.title}</span>
                </div>
                <p className="mt-1 text-xs leading-relaxed text-slate-600">{it.oneLine}</p>
                <div className="mt-1 text-[11px] font-medium text-slate-400">{it.source} ↗</div>
              </a>
            ))}
          </div>
        </Card>
      ) : (
        <div className="rounded-2xl bg-white p-4 text-sm text-slate-500 ring-1 ring-slate-200">{news.summary} — no dated press items in recent months; the signal above is the notable read.</div>
      )}
      <p className="text-[11px] text-slate-400">Gathered from the open web · headlines link to their source · a supplier typically surfaces only a handful of items in six months.</p>
    </div>
  );
}

// Analyst-grade "X-ray": DuPont decomposition of RoE, Piotroski F-score checklist,
// and Altman-Z distress gauge — the sophisticated read on financial health.
function HealthPanel({ a }: { a: Advanced }) {
  const dp = a.dupont;
  const dupontRead = dp
    ? (dp.equityMult != null && dp.equityMult >= 2.5 && (dp.netMargin ?? 0) < 6) ? "Leverage-driven return — fragile; debt is doing the work, not the operations."
      : (dp.netMargin != null && dp.netMargin >= 8 && (dp.equityMult ?? 9) <= 1.6) ? "Margin-driven — real pricing power on a clean balance sheet."
        : (dp.assetTurn != null && dp.assetTurn >= 1.5) ? "Turnover-driven — a lean, asset-light operator."
          : "Balanced mix of margin, efficiency and leverage."
    : "";
  const zColor = a.zZone === "distress" ? "#e11d48" : a.zZone === "grey" ? "#f59e0b" : "#059669";
  const zMark = a.z != null ? Math.max(2, Math.min(98, (Math.min(a.z, 6) / 6) * 100)) : null; // clamp display 0–6
  const fCol = (a.fscore ?? 0) >= 7 ? "text-emerald-600" : (a.fscore ?? 0) >= 4 ? "text-amber-600" : "text-rose-600";
  return (
    <Card title="Financial-health X-ray" sub="DuPont · Piotroski · Altman-Z — analyst-grade signals computed from the filings, no extra data" accent={C.violet}>
      <div className="grid gap-3 lg:grid-cols-3">
        {/* DuPont */}
        <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
          <div className="mb-2 text-[11px] font-bold uppercase tracking-wide text-slate-500">DuPont — where the return comes from</div>
          {dp && dp.roe != null ? (
            <>
              <div className="flex items-baseline justify-between"><span className="text-sm text-slate-500">Return on equity</span><span className="text-2xl font-bold text-violet-700">{dp.roe}%</span></div>
              <div className="mt-2 flex items-stretch gap-1 text-center">
                {[["Net margin", dp.netMargin != null ? dp.netMargin + "%" : "—"], ["× Asset turn", dp.assetTurn != null ? dp.assetTurn + "×" : "—"], ["× Leverage", dp.equityMult != null ? dp.equityMult + "×" : "—"]].map(([k, v]) => (
                  <div key={k} className="flex-1 rounded-lg bg-white p-2 ring-1 ring-slate-200"><div className="font-mono text-sm font-bold text-slate-800">{v}</div><div className="text-[9px] leading-tight text-slate-500">{k}</div></div>
                ))}
              </div>
              <div className="mt-2 text-[11px] leading-snug text-slate-500">{dupontRead}</div>
            </>
          ) : <Empty t="Not enough data." />}
        </div>
        {/* Piotroski */}
        <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
          <div className="mb-2 flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-wide text-slate-500">Piotroski F-score</span><span className={`text-lg font-bold ${fCol}`}>{a.fscore ?? "—"}<span className="text-xs text-slate-400">/9</span></span></div>
          {a.fChecks.length ? (
            <div className="space-y-0.5">
              {a.fChecks.map((c, i) => (
                <div key={i} className="flex items-center gap-1.5 text-[11px]"><span className={c.ok ? "text-emerald-600" : "text-slate-300"}>{c.ok ? "✓" : "○"}</span><span className={c.ok ? "text-slate-700" : "text-slate-400"}>{c.label}</span></div>
              ))}
            </div>
          ) : <Empty t="Needs 2+ years." />}
        </div>
        {/* Altman Z + cash tiles */}
        <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
          <div className="mb-2 flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-wide text-slate-500">Altman-Z distress</span><span className="text-lg font-bold" style={{ color: zColor }}>{a.z ?? "—"} <span className="text-xs capitalize">{a.zZone ?? ""}</span></span></div>
          <div className="relative mt-1 h-2.5 w-full overflow-hidden rounded-full">
            <div className="absolute inset-0 flex"><div className="bg-rose-300" style={{ width: "18%" }} /><div className="bg-amber-200" style={{ width: "25%" }} /><div className="bg-emerald-300" style={{ width: "57%" }} /></div>
            {zMark != null && <div className="absolute top-1/2 h-4 w-1.5 -translate-x-1/2 -translate-y-1/2 rounded bg-slate-900 ring-2 ring-white" style={{ left: `${zMark}%` }} />}
          </div>
          <div className="mt-1 flex justify-between text-[9px] text-slate-400"><span>distress</span><span>grey</span><span>safe →</span></div>
          <div className="mt-3 grid grid-cols-3 gap-1.5 text-center">
            {[["Free cash flow", a.fcfLatest != null ? `₹${Math.round(a.fcfLatest)} Cr` : "—"], ["Op. leverage", a.opLeverage != null ? a.opLeverage + "×" : "—"], ["Accruals", a.accrualsLatest != null ? a.accrualsLatest + "%" : "—"]].map(([k, v]) => (
              <div key={k} className="rounded-lg bg-white p-1.5 ring-1 ring-slate-200"><div className="font-mono text-xs font-bold text-slate-800">{v}</div><div className="text-[9px] leading-tight text-slate-500">{k}</div></div>
            ))}
          </div>
        </div>
      </div>
    </Card>
  );
}

function FinancialsTab({ d }: { d: Detail }) {
  const empByFy = useMemo(() => new Map(d.employees.yearly.map((e) => [e.fy, e.count])), [d]);
  const monthly = d.employees.monthly;
  return (
    <div className="space-y-4">
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="lg:col-span-2"><TrendExplorer fin={d.fin} empByFy={empByFy} /></div>
        {/* self-start: this column is shorter than the explorer beside it, so let it
            end where its content ends instead of stretching into dead white space. */}
        <div className="flex flex-col gap-4 self-start">
          <Card title="Financial-health score" sub="Probe42 · out of 10" accent={C.emerald}>
            <HBars valueLabel={(v) => `${v}/10`} data={[["Growth", d.score.growth], ["Profitability", d.score.profitability], ["Liquidity", d.score.liquidity], ["Solvency", d.score.solvency], ["Efficiency", d.score.efficiency]].map<Slice>(([k, v]) => ({ label: k as string, value: (v as number) ?? 0, color: ((v as number) ?? 0) >= 7 ? C.emerald : ((v as number) ?? 0) >= 4 ? C.amber : C.rose }))} />
          </Card>
          {monthly.length > 1 && (
            <Card title="Headcount" sub={`last ${monthly.length} months · EPFO filings`} accent={C.teal}>
              <AreaLine data={monthly.map<Slice>((m) => ({ label: m.month, value: m.count, color: TEAL }))} color={TEAL} valueLabel={(v) => `${Math.round(v)}`} height={150} />
            </Card>
          )}
        </div>
      </div>
      {d.advanced && <HealthPanel a={d.advanced} />}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card title="Where every ₹100 of sales goes" sub="cost structure each year · a fatter green band = more room on price" accent={C.amber}>
          <CostMix fin={d.fin} />
        </Card>
        <Card title="Cash generation" sub="does the business actually throw off cash? · operating vs investing vs financing · ₹ crore" accent={C.sky}>
          <MultiLine xLabels={d.fin.map((f) => f.fy)} valueLabel={(v) => `₹${Math.round(v)} Cr`} height={260}
            series={[
              { name: "Operating", color: C.emerald, points: d.fin.map((f) => n(f.cf.operating)) },
              { name: "Investing", color: C.sky, points: d.fin.map((f) => n(f.cf.investing)) },
              { name: "Financing", color: C.amber, points: d.fin.map((f) => n(f.cf.financing)) },
            ]} />
        </Card>
      </div>
      {(d.revenueMix || d.capexWip || d.managerialPay || d.assetAge || d.powerCost) && <RevenueMixCard d={d} />}
      <Card title="Full financials — every line, every year" sub="income statement · balance sheet · cash flow · ratios — straight from MCA filings · scroll →" accent="#334155">
        <FinTable fin={d.fin} />
      </Card>
    </div>
  );
}

// What the revenue actually IS — manufactured vs bought-in vs services, and how
// much sits abroad. This decides how much price room exists at all: a trader can
// only give away its markup, a maker owns the whole conversion spread. Sits
// alongside the cash signals that change the same conversation.
function RevenueMixCard({ d }: { d: Detail }) {
  const m = d.revenueMix;
  const parts = m ? ([
    { k: "Manufactured", v: m.manufacturedPct ?? 0, cr: m.manufacturedCr, c: C.emerald },
    { k: "Bought in & resold", v: m.tradedPct ?? 0, cr: m.tradedCr, c: C.amber },
    { k: "Services", v: m.servicesPct ?? 0, cr: m.servicesCr, c: C.sky },
  ].filter((p) => p.v > 0)) : [];
  const chips: [string, string, string][] = [];
  if (m && (m.exportPct ?? 0) > 0) chips.push(["Export share", `${m.exportPct}%`, `₹${m.exportCr} Cr sold abroad — demand that doesn't depend on Indian buyers`]);
  if (d.capexWip) chips.push(["Capacity being built", `₹${d.capexWip.amountCr} Cr`, `${d.capexWip.pctOfFixedAssets}% of fixed assets is paid-for capacity not yet producing — they'll need volume to absorb it`]);
  if (d.managerialPay) chips.push(["Owner pay", `₹${d.managerialPay.amountCr} Cr`, d.managerialPay.pctOfProfit != null ? `${d.managerialPay.pctOfProfit}% of profit after tax is taken out as managerial remuneration` : "managerial remuneration"]);
  if (d.proposedDividend) chips.push(["Dividend", "proposed", "cash being distributed to shareholders rather than retained"]);
  if (d.assetAge?.depreciatedPct != null) chips.push(["Plant depreciated", `${d.assetAge.depreciatedPct}%`, `₹${d.assetAge.netCr} Cr left of a ₹${d.assetAge.grossCr} Cr gross asset base — how much life is still in the plant`]);
  if (d.powerCost?.pctOfRevenue != null) chips.push(["Power & fuel", `${d.powerCost.pctOfRevenue}% of revenue`, `₹${d.powerCost.amountCr} Cr — how exposed they are to tariff moves`]);
  return (
    <Card title="What they actually sell — and where the cash goes" sub={`${m ? m.fy + " revenue split · " : ""}a maker owns its conversion margin; a reseller only owns the markup`} accent={C.emerald}>
      {parts.length > 0 && (
        <>
          <div className="flex h-5 w-full overflow-hidden rounded-full">
            {parts.map((p) => <div key={p.k} className="h-5" style={{ width: `${p.v}%`, background: p.c }} title={`${p.k}: ${p.v}%`} />)}
          </div>
          <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1.5">
            {parts.map((p) => (
              <span key={p.k} className="flex items-center gap-1.5 text-sm text-slate-600">
                <span className="h-2.5 w-2.5 rounded-[3px]" style={{ background: p.c }} />
                {p.k} <span className="font-mono font-semibold text-slate-900">{p.v}%</span>
                {p.cr != null && <span className="font-mono text-xs text-slate-400">₹{p.cr} Cr</span>}
              </span>
            ))}
          </div>
        </>
      )}
      {chips.length > 0 && (
        <div className={`flex flex-wrap gap-2 ${parts.length ? "mt-4 border-t border-slate-100 pt-3" : ""}`}>
          {chips.map(([k, v, hint]) => (
            <span key={k} title={hint} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-50 px-2.5 py-1.5 text-xs ring-1 ring-slate-200">
              <span className="text-slate-500">{k}</span><span className="font-mono font-bold text-slate-800">{v}</span>
            </span>
          ))}
        </div>
      )}
    </Card>
  );
}

// Cost structure as a 100%-stacked bar per year — shows, at a glance, how much of
// each sales rupee is eaten by materials/people/overheads and how much is left as
// profit. A widening green (profit) band is a direct "they can give on price" cue.
function CostMix({ fin }: { fin: FinRow[] }) {
  const parts = [
    { k: "Materials", c: "#0d9488", get: (f: FinRow) => (n(f.materialCost) ?? 0) + (n(f.purchases) ?? 0) },
    { k: "People", c: "#6366f1", get: (f: FinRow) => n(f.employeeCost) ?? 0 },
    { k: "Other opex", c: "#f59e0b", get: (f: FinRow) => n(f.otherExpense) ?? 0 },
    { k: "Profit (EBITDA)", c: "#10b981", get: (f: FinRow) => Math.max(0, n(f.ebitda) ?? 0) },
  ];
  const rows = fin.map((f) => {
    const vals = parts.map((p) => p.get(f));
    const tot = vals.reduce((a, b) => a + b, 0) || 1;
    return { fy: f.fy, segs: parts.map((p, i) => ({ ...p, pct: (vals[i] / tot) * 100 })) };
  });
  return (
    <div>
      <div className="mb-2 flex flex-wrap gap-x-3 gap-y-1 text-[11px]">
        {parts.map((p) => <span key={p.k} className="inline-flex items-center gap-1 text-slate-600"><span className="h-2.5 w-2.5 rounded-sm" style={{ background: p.c }} />{p.k}</span>)}
      </div>
      <div className="space-y-1">
        {rows.map((r) => (
          <div key={r.fy} className="flex items-center gap-2">
            <span className="w-9 shrink-0 font-mono text-[10px] text-slate-400">{r.fy}</span>
            <div className="flex h-4 flex-1 overflow-hidden rounded ring-1 ring-slate-200">
              {r.segs.map((s) => s.pct > 0.5 && <div key={s.k} title={`${s.k}: ${Math.round(s.pct)}% of sales`} style={{ width: `${s.pct}%`, background: s.c }} />)}
            </div>
            <span className="w-9 shrink-0 text-right font-mono text-[10px] font-semibold text-emerald-600" title="profit share of sales">{Math.round(r.segs[3].pct)}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}
function FinTable({ fin }: { fin: FinRow[] }) {
  // dir: +1 = higher is better, -1 = lower is better, 0 = neutral (no colour)
  type R = { label: string; get: (f: FinRow) => number | null; fmt: (v: number | null) => string; dir: number; indent?: boolean };
  const x2 = (v: number | null) => (v == null ? "—" : v.toFixed(2));
  const add = (a: number | null | undefined, b: number | null | undefined) => { const x = n(a), y = n(b); return x == null && y == null ? null : (x ?? 0) + (y ?? 0); };
  const sections: { title: string; rows: R[] }[] = [
    { title: "Income statement", rows: [
      { label: "Revenue", get: (f) => f.revenue, fmt: cr, dir: 1 },
      { label: "Material + purchases", get: (f) => add(f.materialCost, f.purchases), fmt: cr, dir: 0, indent: true },
      { label: "Employee cost", get: (f) => n(f.employeeCost), fmt: cr, dir: 0, indent: true },
      { label: "Other expenses", get: (f) => n(f.otherExpense), fmt: cr, dir: 0, indent: true },
      { label: "EBITDA", get: (f) => f.ebitda, fmt: cr, dir: 1 },
      { label: "Depreciation", get: (f) => n(f.depreciation), fmt: cr, dir: 0, indent: true },
      { label: "Interest", get: (f) => n(f.interest), fmt: cr, dir: -1, indent: true },
      { label: "Tax", get: (f) => n(f.tax), fmt: cr, dir: 0, indent: true },
      { label: "Net profit (PAT)", get: (f) => f.pat, fmt: cr, dir: 1 },
    ] },
    { title: "Balance sheet", rows: [
      { label: "Fixed assets", get: (f) => f.bs.tangibleAssets, fmt: cr, dir: 0 },
      { label: "Inventory", get: (f) => f.bs.inventory, fmt: cr, dir: 0 },
      { label: "Receivables", get: (f) => f.bs.receivables, fmt: cr, dir: 0 },
      { label: "Cash & equivalents", get: (f) => f.bs.cash, fmt: cr, dir: 1 },
      { label: "Total assets", get: (f) => f.bs.totalAssets, fmt: cr, dir: 0 },
      { label: "Equity / net worth", get: (f) => f.bs.equity, fmt: cr, dir: 1 },
      { label: "Total debt", get: (f) => f.bs.debt, fmt: cr, dir: -1 },
      { label: "Payables", get: (f) => f.bs.payables, fmt: cr, dir: 0 },
    ] },
    { title: "Cash flow", rows: [
      { label: "Operating", get: (f) => f.cf.operating, fmt: cr, dir: 1 },
      { label: "Investing", get: (f) => f.cf.investing, fmt: cr, dir: 0 },
      { label: "Financing", get: (f) => f.cf.financing, fmt: cr, dir: 0 },
    ] },
    { title: "Key ratios", rows: [
      { label: "EBITDA margin", get: (f) => f.r.ebitdaMargin, fmt: pct, dir: 1 },
      { label: "Net margin", get: (f) => f.r.netMargin, fmt: pct, dir: 1 },
      { label: "Gross margin", get: (f) => f.r.grossMargin, fmt: pct, dir: 1 },
      { label: "RoCE", get: (f) => f.r.roce, fmt: pct, dir: 1 },
      { label: "RoE", get: (f) => f.r.roe, fmt: pct, dir: 1 },
      { label: "Debt / equity", get: (f) => f.r.debtEquity, fmt: x2, dir: -1 },
      { label: "Interest cover", get: (f) => f.r.interestCover, fmt: xN, dir: 1 },
      { label: "Current ratio", get: (f) => f.r.currentRatio, fmt: x2, dir: 1 },
      { label: "Quick ratio", get: (f) => f.r.quickRatio, fmt: x2, dir: 1 },
      { label: "Collects (DSO)", get: (f) => f.r.debtorDays, fmt: days, dir: -1 },
      { label: "Pays (DPO)", get: (f) => f.r.payableDays, fmt: days, dir: 0 },
      { label: "Inventory days", get: (f) => f.r.inventoryDays, fmt: days, dir: -1 },
      { label: "Cash cycle", get: (f) => f.r.cashConversion, fmt: days, dir: -1 },
    ] },
  ];
  const move = (r: R, i: number): { cls: string; arrow: string } => {
    if (r.dir === 0 || i === 0) return { cls: "text-slate-800", arrow: "" };
    const v = r.get(fin[i]), p = r.get(fin[i - 1]);
    if (v == null || p == null) return { cls: "text-slate-800", arrow: "" };
    const chg = p === 0 ? (v > 0 ? 1 : v < 0 ? -1 : 0) : (v - p) / Math.abs(p);
    if (Math.abs(chg) < 0.02) return { cls: "text-slate-400", arrow: "" };       // stable
    const better = r.dir === 1 ? chg > 0 : chg < 0;
    return { cls: better ? "text-emerald-600" : "text-rose-500", arrow: v > p ? " ▲" : " ▼" };
  };
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[760px] border-collapse text-sm">
        <thead>
          <tr className="text-left">
            <th className="sticky left-0 z-10 bg-white px-3 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">Metric</th>
            {fin.map((f) => <th key={f.fy} className="border-b-2 border-teal-500/40 bg-teal-50/60 px-3 py-2 text-right font-mono text-xs font-bold text-teal-800">{f.fy}</th>)}
          </tr>
        </thead>
        <tbody>
          {sections.map((sec) => (
            <Fragment key={sec.title}>
              <tr><td colSpan={fin.length + 1} className="sticky left-0 bg-slate-100/80 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-slate-500">{sec.title}</td></tr>
              {sec.rows.map((r) => (
                <tr key={r.label} className="border-t border-slate-100 hover:bg-slate-50/70">
                  <td className={`sticky left-0 z-10 bg-white px-3 py-1.5 ${r.indent ? "pl-6 font-normal text-slate-500" : "font-semibold text-slate-700"}`}>{r.label}</td>
                  {fin.map((f, i) => { const m = move(r, i); return <td key={f.fy} className={`whitespace-nowrap px-3 py-1.5 text-right font-mono tabular-nums ${m.cls}`}>{r.fmt(r.get(f))}<span className="text-[9px]">{m.arrow}</span></td>; })}
                </tr>
              ))}
            </Fragment>
          ))}
        </tbody>
      </table>
      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 px-1 text-[11px] text-slate-400">
        <span><b className="text-emerald-600">▲ green</b> = better than the year before</span>
        <span><b className="text-rose-500">▼ red</b> = worse</span>
        <span><b className="text-slate-400">grey</b> = about the same</span>
      </div>
    </div>
  );
}

/* ==================================================================== PEERS */
function PeersTab({ d }: { d: Detail }) {
  // Registry peer names are ALL-CAPS; title-case them so they read like the rest
  // of the app instead of shouting inside a truncated bar label.
  const peerBars = d.peers.named.map<Slice>((p) => ({ label: titleCase(p.name), value: p.revenueCr, color: p.isSelf ? TEAL : "#cbd5e1" }));
  const rows: [string, string, boolean][] = [["ebitdaMargin", "EBITDA margin", true], ["netMargin", "Net margin", true], ["roce", "RoCE", true], ["roe", "RoE", true], ["debtorDays", "Collection days", false], ["payableDays", "Payment days", false], ["cashConversion", "Cash cycle", false], ["debtEquity", "Debt / equity", false], ["inventoryDays", "Inventory days", false]];
  return (
    // items-start: the peer bar list is shorter than the ratio panel beside it, so
    // don't stretch it into a card with a tall empty tail.
    <div className="grid items-start gap-4 lg:grid-cols-2">
      <Card title="Peers by revenue" sub={`${d.peers.segment ?? "closest peers"} · ${d.peers.sampleSize ?? d.peers.named.length} in Probe's set · ₹ crore`} accent={TEAL}>
        <HBars data={peerBars} valueLabel={(v) => `₹${Math.round(v)} Cr`} />
      </Card>
      <Card title="This company vs the peer median" sub="latest year · green = the side that helps us" accent={C.sky}>
        <div className="space-y-2.5">
          {rows.map(([k, label, higherBetter]) => (
            <Versus key={k} label={label} self={n(d.vsMedian.self[k])} median={n(d.vsMedian.median[k])} unit={k.includes("Days") || k === "cashConversion" ? "d" : k === "debtEquity" ? "" : "%"} higherSelfBetter={higherBetter} />
          ))}
        </div>
      </Card>
      {d.peers.benchmarks.length > 1 && <PeerGapTrend benchmarks={d.peers.benchmarks} />}
    </div>
  );
}

// Pick ANY benchmarked ratio and watch this company vs the peer median across every
// year on file — not just EBITDA margin. This is the "are we negotiating with a
// leader or a laggard, and is the gap widening?" view.
function PeerGapTrend({ benchmarks }: { benchmarks: Detail["peers"]["benchmarks"] }) {
  const METRICS: { k: string; label: string; unit: string; higherBetter: boolean }[] = [
    { k: "ebitdaMargin", label: "EBITDA margin", unit: "%", higherBetter: true },
    { k: "netMargin", label: "Net margin", unit: "%", higherBetter: true },
    { k: "grossMargin", label: "Gross margin", unit: "%", higherBetter: true },
    { k: "roce", label: "RoCE", unit: "%", higherBetter: true },
    { k: "roe", label: "RoE", unit: "%", higherBetter: true },
    { k: "revenueGrowth", label: "Revenue growth", unit: "%", higherBetter: true },
    { k: "debtorDays", label: "Collection days", unit: "d", higherBetter: false },
    { k: "payableDays", label: "Payment days", unit: "d", higherBetter: false },
    { k: "cashConversion", label: "Cash cycle", unit: "d", higherBetter: false },
    { k: "debtEquity", label: "Debt / equity", unit: "x", higherBetter: false },
    { k: "currentRatio", label: "Current ratio", unit: "x", higherBetter: true },
  ].filter((m) => benchmarks.some((b) => n(b.self[m.k]) != null || n(b.median[m.k]) != null));
  const [mk, setMk] = useState(METRICS[0]?.k ?? "ebitdaMargin");
  const met = METRICS.find((m) => m.k === mk) ?? METRICS[0];
  const asc = [...benchmarks].reverse(); // oldest → newest
  const fmt = met.unit === "%" ? (v: number) => `${v}%` : met.unit === "d" ? (v: number) => `${Math.round(v)} d` : (v: number) => v.toFixed(2);
  const self = asc.map((b) => n(b.self[mk]));
  const median = asc.map((b) => n(b.median[mk]));
  const lastSelf = [...self].reverse().find((v) => v != null) ?? null;
  const lastMed = [...median].reverse().find((v) => v != null) ?? null;
  const ahead = lastSelf != null && lastMed != null ? (met.higherBetter ? lastSelf > lastMed : lastSelf < lastMed) : null;
  return (
    <Card title="This company vs the peer median — over time" sub="pick any metric · every benchmarked year on file" accent={C.indigo} className="lg:col-span-2">
      <div className="mb-3 flex flex-wrap gap-1.5">
        {METRICS.map((m) => <button key={m.k} onClick={() => setMk(m.k)} className={`rounded-lg px-2.5 py-1 text-xs font-semibold transition ${mk === m.k ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{m.label}</button>)}
      </div>
      {ahead != null && (
        <div className={`mb-3 inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-medium ${ahead ? "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200" : "bg-rose-50 text-rose-700 ring-1 ring-rose-200"}`}>
          {ahead ? "✓ Ahead of peers" : "▼ Behind peers"} on {met.label.toLowerCase()} — {fmt(lastSelf as number)} vs {fmt(lastMed as number)} median
        </div>
      )}
      <MultiLine xLabels={asc.map((b) => b.year)} valueLabel={fmt} height={260}
        series={[{ name: "This company", color: TEAL, points: self }, { name: "Peer median", color: C.slate, points: median }]} />
    </Card>
  );
}

/* ================================================================== OWNERS */
// The registry lists one row per appointment, so a person who is both Managing
// Director and CEO appeared twice with identical numbers. Collapse to one row per
// person and join their roles.
function mergeDirectors(list: Detail["directors"]): Detail["directors"] {
  const by = new Map<string, Detail["directors"][number]>();
  for (const p of list) {
    const key = p.name.trim().toLowerCase();
    const seen = by.get(key);
    if (!seen) { by.set(key, { ...p }); continue; }
    const roles = new Set([seen.designation, p.designation].filter(Boolean) as string[]);
    seen.designation = [...roles].join(" · ");
    seen.since = seen.since ?? p.since;
    seen.age = seen.age || p.age;
    seen.ownPct = seen.ownPct ?? p.ownPct;
    if (p.otherCount > seen.otherCount) { seen.otherCount = p.otherCount; seen.others = p.others; }
  }
  return [...by.values()];
}

function OwnersTab({ d }: { d: Detail }) {
  const people = mergeDirectors(d.directors);
  const shares = d.shareholders.map<Slice>((s, i) => ({ label: titleCase(s.name), value: s.pct, color: SH_COLORS[i % SH_COLORS.length], sub: s.type }));
  const grp = (["holding", "subsidiaries", "associates", "jointVentures"] as const).map((k) => ({ k, items: d.group[k] ?? [] })).filter((g) => g.items.length);
  // Probe's promoter/public split is unreliable for wholly-owned subsidiaries
  // (it can report >100%). Only show it when it's sane; else fall back to a count.
  const valid = (v: number | null) => v != null && v >= 0 && v <= 100;
  const ownSub = valid(d.ownership.promoterPct) || valid(d.ownership.publicPct)
    ? `promoter ${valid(d.ownership.promoterPct) ? pct(d.ownership.promoterPct) : "—"} · public ${valid(d.ownership.publicPct) ? pct(d.ownership.publicPct) : "—"}`
    : `${d.shareholders.length} holder${d.shareholders.length === 1 ? "" : "s"} on file`;
  return (
    <div className="grid items-start gap-4 lg:grid-cols-2 xl:grid-cols-3">
      <Card title="Shareholding (>5%)" sub={ownSub} accent={C.indigo}>
        {shares.length ? <Donut data={shares} centerValue={`${shares.length}`} centerLabel="holders" unit="%" /> : <Empty t="No disclosed holders >5%." />}
      </Card>
      <Card title="Who runs it — board & overboarding" sub={`${people.length} on the board · how many other live companies each also sits on`} accent={C.violet} className="xl:col-span-2">
        {people.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[560px] border-collapse text-sm">
              <thead>
                <tr className="border-b border-slate-200 bg-slate-50 text-left text-xs font-bold uppercase tracking-wider text-slate-500">
                  <th className="px-3 py-2">Director</th><th className="px-3 py-2">Role</th>
                  <th className="px-3 py-2 text-center">Since</th><th className="px-3 py-2 text-center">Age</th>
                  <th className="px-3 py-2 text-center">Owns</th><th className="px-3 py-2 text-center">Other boards</th><th className="px-3 py-2">Also sits on</th>
                </tr>
              </thead>
              <tbody>
                {[...people].sort((a, b) => b.otherCount - a.otherCount).map((p, i) => {
                  const tone = p.otherCount >= 6 ? "bg-rose-100 text-rose-700" : p.otherCount >= 3 ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-500";
                  return (
                    <tr key={i} className="border-t border-slate-100 hover:bg-slate-50/70">
                      <td className="px-3 py-2 font-semibold text-slate-800">{titleCase(p.name)}</td>
                      <td className="px-3 py-2 text-slate-600">{p.designation ?? "Director"}</td>
                      <td className="px-3 py-2 text-center font-mono text-slate-500">{p.since ?? "—"}</td>
                      <td className="px-3 py-2 text-center font-mono text-slate-500">{p.age ? p.age : "—"}</td>
                      <td className={`px-3 py-2 text-center font-mono ${p.ownPct ? "font-semibold text-teal-700" : "text-slate-400"}`}>{p.ownPct != null ? `${p.ownPct}%` : "—"}</td>
                      <td className="px-3 py-2 text-center"><span className={`inline-block min-w-[1.75rem] rounded-full px-2 py-0.5 text-xs font-bold ${tone}`}>{p.otherCount}</span></td>
                      <td className="px-3 py-2 text-xs text-slate-500">{p.others.length ? <span title={p.others.map(titleCase).join(", ")}>{p.others.slice(0, 3).map(titleCase).join(", ")}{p.otherCount > 3 ? ` +${p.otherCount - 3} more` : ""}</span> : <span className="text-slate-300">—</span>}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <p className="mt-2 px-1 text-[11px] text-slate-400">"Other boards" = other live companies this person is a director of. <span className="font-medium text-amber-600">Amber 3–5</span> · <span className="font-medium text-rose-600">red 6+</span> = a stretched (overboarded) director — a governance signal worth a look.</p>
          </div>
        ) : <Empty t="No current directors on file." />}
      </Card>
      {grp.length > 0 && (
        <Card title="Group structure" sub="holding · subsidiaries · associates · JVs" accent={TEAL}>
          <div className="space-y-2.5 text-sm">
            {grp.map((g) => (
              <div key={g.k}>
                <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{g.k}</div>
                <ul className="mt-0.5 space-y-0.5">{g.items.map((it, i) => <li key={i} className="flex justify-between gap-2 text-slate-700"><span className="truncate">{it.name}</span>{it.pct != null && <span className="shrink-0 font-mono text-slate-500">{it.pct}%</span>}</li>)}</ul>
              </div>
            ))}
          </div>
        </Card>
      )}
      {d.relatedParty.count > 0 && (
        <Card title="Related-party dealings" sub={`${d.relatedParty.year ?? ""} · ${d.relatedParty.count} transactions · ${cr(d.relatedParty.totalCr)}`} accent={C.amber}>
          <ul className="space-y-1.5 text-sm">{d.relatedParty.top.map((t, i) => <li key={i} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-1.5"><span className="min-w-0"><span className="block truncate text-slate-800">{t.name}</span><span className="text-[11px] text-slate-400">{t.kind}</span></span><span className="shrink-0 font-mono text-slate-600">{cr(t.amountCr)}</span></li>)}</ul>
        </Card>
      )}
      {d.allotments.length > 0 && (
        <Card title="Capital raised" sub="share allotments on record" accent={C.emerald}>
          <ul className="space-y-1.5 text-sm">{d.allotments.map((a, i) => <li key={i} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-1.5"><span className="min-w-0"><span className="block truncate text-slate-800">{a.type ?? a.instrument}</span><span className="text-[11px] text-slate-400">{a.date}</span></span><span className="shrink-0 font-mono text-slate-600">{cr(a.amountCr)}</span></li>)}</ul>
        </Card>
      )}
    </div>
  );
}

/* =================================================================== RISK */
function CreditRatingCard({ rt }: { rt: Detail["creditRating"] }) {
  if (!rt) return <Card title="Credit rating" sub="external agency view" accent={C.slate}><Empty t="Not externally rated — no CRISIL / CARE / ICRA / Acuité rating on file." /></Card>;
  const bad = rt.flags.isDefault || rt.flags.subInvestmentGrade || rt.flags.inc;
  const gradeTone = rt.flags.isDefault || rt.flags.subInvestmentGrade ? "bg-rose-100 text-rose-700 ring-rose-200" : rt.flags.inc || rt.flags.downgraded ? "bg-amber-100 text-amber-700 ring-amber-200" : "bg-emerald-100 text-emerald-700 ring-emerald-200";
  const chips: [string, boolean, "bad" | "warn" | "good"][] = [
    ["In default", !!rt.flags.isDefault, "bad"], ["Sub-investment-grade", !!rt.flags.subInvestmentGrade, "bad"],
    ["Issuer Not Cooperating", !!rt.flags.inc, "warn"], ["Downgraded over time", !!rt.flags.downgraded, "warn"],
    ["Rating withdrawn", !!rt.flags.withdrawn, "warn"], ["Investment-grade", !!rt.flags.strong, "good"],
  ];
  const cTone = { bad: "bg-rose-50 text-rose-700 ring-rose-200", warn: "bg-amber-50 text-amber-700 ring-amber-200", good: "bg-emerald-50 text-emerald-700 ring-emerald-200" };
  return (
    <Card title="Credit rating" sub={`${rt.agency ?? "Agency"}${rt.date ? ` · as of ${rt.date}` : ""}`} accent={bad ? C.rose : C.emerald}>
      <div className="flex items-center gap-3">
        <span className={`rounded-lg px-3 py-1.5 text-lg font-bold ring-1 ${gradeTone}`}>{rt.grade ?? "—"}</span>
        <div className="min-w-0 text-xs text-slate-500"><span className="block truncate text-slate-600">{rt.gradeText}</span>{rt.ratedAmountCr != null && <span>₹{rt.ratedAmountCr} Cr of facilities rated</span>}{rt.outlook && <span className={`ml-1 font-semibold ${/negative/i.test(rt.outlook) ? "text-rose-600" : /positive/i.test(rt.outlook) ? "text-emerald-600" : "text-slate-500"}`}>· {rt.outlook} outlook</span>}</div>
      </div>
      <div className="mt-2.5 flex flex-wrap gap-1.5">{chips.filter(([, on]) => on).map(([label, , t]) => <span key={label} className={`rounded-md px-1.5 py-0.5 text-[11px] font-semibold ring-1 ${cTone[t]}`}>{label}</span>)}</div>
      {rt.facilities.length > 0 && (
        // Each facility carries the agency's full outlook string ("AA- (Under
        // Rating Watch with Developing Implications)"). Repeating it on every line
        // both overflowed the card and said the same thing six times — the outlook
        // is already on the grade above, so show just the code and the amount.
        <ul className="mt-3 space-y-1 border-t border-slate-100 pt-2 text-xs">
          {rt.facilities.map((f, i) => (
            <li key={i} className="flex items-center justify-between gap-2" title={`${f.loan ?? "Facility"} — ${f.rating}`}>
              <span className="truncate text-slate-600">{f.loan || `Facility ${i + 1}`}</span>
              <span className="shrink-0 font-mono text-slate-500">
                <span className="font-semibold text-slate-700">{(f.rating ?? "").replace(/\s*\([^)]*\)/g, "").trim() || "—"}</span>
                {f.amountCr != null ? ` · ₹${f.amountCr} Cr` : ""}
              </span>
            </li>
          ))}
        </ul>
      )}
    </Card>
  );
}
function RiskTab({ d }: { d: Detail }) {
  return (
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
      <CreditRatingCard rt={d.creditRating} />
      <Card title="Compliance flags" sub="statutory & bureau signals" accent={C.rose}>
        <div className="flex flex-wrap gap-2">
          <Flag on={d.flags.gstDelay} bad="GST filing delays" good="GST filed on time" />
          <Flag on={d.flags.epfDelay} bad="EPF payment delays" good="EPF paid on time" />
          <Flag on={d.flags.bureauDefaults} bad="Bureau default" good="No bureau default" />
          <Flag on={d.flags.pendingCases} bad="Pending cases" good="No pending case" />
          <Flag on={d.flags.severeCases} bad="Severe cases" good="No severe case" />
          <Flag on={d.flags.struckOff} bad="Struck off" good="Active on register" />
        </div>
        <dl className="mt-3 space-y-1.5 text-sm">
          <Row k="GST registrations" v={`${d.gst.total} · ${d.gst.onTime} filing regularly`} />
          {d.agedReceivables?.amountCr != null && <Row k="Receivables > 6 months old" v={cr(d.agedReceivables.amountCr)} />}
          {d.forex && (d.forex.spendCr != null || d.forex.earnCr != null) && <Row k="Forex spend / earn" v={`${cr(d.forex.spendCr)} / ${cr(d.forex.earnCr)}`} />}
          <Row k="Paid-up capital" v={cr(d.paidUpCr)} />
        </dl>
      </Card>
      <Card title="Secured lenders" sub={d.charges.count ? `${d.charges.count} open charge${d.charges.count > 1 ? "s" : ""} · ${cr(d.charges.sumCr)}${d.charges.everCreated ? ` · ${d.charges.everCreated} filed / ${d.charges.satisfied ?? 0} cleared over time` : ""}` : (d.charges.everCreated ? `no open charges · ${d.charges.everCreated} filed & ${d.charges.satisfied ?? 0} cleared over time` : "no secured borrowing on record")} accent={C.amber}>
        {d.charges.list.length ? (
          <ul className="space-y-1.5 text-sm">{d.charges.list.map((c, i) => <li key={i} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-1.5"><span className="min-w-0"><span className="block truncate text-slate-800">{titleCase(c.holder)}</span><span className="text-[11px] text-slate-400">{c.date} · {c.type}</span></span><span className="shrink-0 font-mono text-slate-600">{cr(c.amountCr)}</span></li>)}</ul>
        ) : <Empty t="Unsecured — no lender charges filed." />}
      </Card>
      <Card title="Pays its own suppliers?" sub="MSME dues left unpaid past 45 days (MCA MSME-1)" accent={C.amber}>
        {d.paymentBehaviour.hasData ? (
          <div className="space-y-2 text-sm">
            {/* when the latest period IS the worst on record, one row says it —
                printing both produced two identical lines. */}
            <dl className="space-y-1.5">
              <Row k={`Overdue now${d.paymentBehaviour.latestPeriod ? ` (${d.paymentBehaviour.latestPeriod})` : ""}`} v={lk(d.paymentBehaviour.latestDueLakh)} />
              {!(d.paymentBehaviour.latestPeriod === d.paymentBehaviour.worstPeriod && d.paymentBehaviour.latestDueLakh === d.paymentBehaviour.worstLakh) && (
                <Row k={`Worst period${d.paymentBehaviour.worstPeriod ? ` (${d.paymentBehaviour.worstPeriod})` : ""}`} v={lk(d.paymentBehaviour.worstLakh)} />
              )}
            </dl>
            {d.paymentBehaviour.latestPeriod === d.paymentBehaviour.worstPeriod && <p className="text-xs text-slate-400">This is also the worst period on record.</p>}
            {d.paymentBehaviour.delayedSuppliers.length > 0 && <div className="text-xs text-slate-500">Recently kept waiting: {d.paymentBehaviour.delayedSuppliers.map((s) => titleCase(s)).join(", ")}</div>}
          </div>
        ) : <div className="rounded-lg bg-emerald-50 px-2.5 py-2 text-sm text-emerald-800 ring-1 ring-emerald-100">✓ No overdue MSME dues reported — pays its small suppliers on time.</div>}
      </Card>
      {d.financialDisputes.count > 0 && (
        <Card title="Financial disputes" sub={`${d.financialDisputes.count} recovery/default case${d.financialDisputes.count > 1 ? "s" : ""} · ${d.financialDisputes.payable} against them · ${d.financialDisputes.receivable} they filed`} accent={d.financialDisputes.payable > 0 ? C.rose : C.amber}>
          <ul className="space-y-1.5 text-sm">
            {d.financialDisputes.list.map((f, i) => (
              <li key={i} className="flex items-start justify-between gap-3 border-b border-slate-100 pb-1.5">
                <span className="min-w-0">
                  <span className="block truncate text-slate-800">{f.counterparty || f.type || "—"}</span>
                  <span className="text-[11px] text-slate-400">{f.direction === "payable" ? "⚠ pursued against them" : "↳ they're recovering"}{f.verdict ? ` · ${f.verdict.toLowerCase()}` : ""}{f.date ? ` · ${f.date}` : ""}</span>
                </span>
                {f.amountCr != null && <span className="shrink-0 font-mono text-slate-600">{cr(f.amountCr)}</span>}
              </li>
            ))}
          </ul>
        </Card>
      )}
      <Card title={`Litigation — ${d.legal.count} case${d.legal.count !== 1 ? "s" : ""} on record`} sub={`${d.legal.high} high-severity · ${d.legal.against} filed against them`} accent={C.rose} className="lg:col-span-2 xl:col-span-3">
        {d.legal.list.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] border-collapse text-sm">
              <thead><tr className="border-b border-slate-200 text-left text-xs font-bold uppercase tracking-wider text-slate-500"><th className="px-3 py-2">Severity</th><th className="px-3 py-2">Counterparty</th><th className="px-3 py-2">Court</th><th className="px-3 py-2">Type</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Date</th></tr></thead>
              <tbody>{d.legal.list.map((c, i) => (
                <tr key={i} className="border-t border-slate-100">
                  <td className="px-3 py-1.5"><span className={`rounded-md px-1.5 py-0.5 text-xs font-medium ${c.severity === "high" ? "bg-rose-100 text-rose-700" : c.severity === "medium" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{c.severity}</span></td>
                  <td className="max-w-[220px] truncate px-3 py-1.5 text-slate-700" title={c.counterparty}>{c.counterparty || "—"}</td>
                  <td className="max-w-[200px] truncate px-3 py-1.5 text-slate-500" title={c.court}>{c.court}</td>
                  <td className="px-3 py-1.5 text-slate-500">{c.type}</td><td className="px-3 py-1.5 text-slate-500">{c.status}</td><td className="whitespace-nowrap px-3 py-1.5 font-mono text-slate-500">{c.date}</td>
                </tr>
              ))}</tbody>
            </table>
          </div>
        ) : <Empty t="No litigation on record." />}
      </Card>
    </div>
  );
}

/* ================================================================== ABOUT */
function AboutTab({ d }: { d: Detail }) {
  return (
    <div className="grid gap-4 lg:grid-cols-3">
      <Card title="What they do" sub={[...new Set([d.industry, d.segment, ...(d.segments ?? []), d.activityGroup].filter(Boolean))].join(" · ") || "business profile"} accent={TEAL} className="lg:col-span-2">
        {d.description ? <p className="text-sm leading-relaxed text-slate-600">{d.description}</p> : <Empty t="No description on file." />}
        {d.gstNature?.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-1.5">
            {d.gstNature.map((t) => <span key={t} className="rounded-md bg-teal-50 px-2 py-0.5 text-[11px] font-medium text-teal-800 ring-1 ring-teal-100">{t}</span>)}
          </div>
        )}
        {d.activities.length > 0 && <div className="mt-3 space-y-1">{d.activities.map((a, i) => <div key={i} className="flex justify-between gap-3 text-sm"><span className="text-slate-600">{a.desc}</span>{a.pct != null && <span className="shrink-0 font-mono text-slate-400">{a.pct}% of turnover</span>}</div>)}</div>}
      </Card>
      {/* The header used to carry the CIN, listing status and former-name trail.
          They belong here, where someone actually looking them up will find them. */}
      <Card title="Registry" sub="MCA basics" accent="#334155">
        <dl className="space-y-1.5 text-sm">
          {d.cin && <Row k="CIN" v={d.cin} />}
          <Row k="Type" v={d.classification ?? "—"} /><Row k="Status" v={d.status ?? "—"} />
          <Row k="Incorporated" v={d.incorporation ?? "—"} /><Row k="Paid-up capital" v={cr(d.paidUpCr)} /><Row k="Authorised capital" v={cr(d.authorizedCr)} />
          <Row k="Last AGM" v={d.lastAgm ?? "—"} /><Row k="Last filing" v={d.lastFiling ?? "—"} />
          {d.website && <Row k="Website" v={d.website.replace(/^https?:\/\//, "")} />}
          <Row k="Registered" v={[d.city && titleCase(d.city), d.state && titleCase(d.state)].filter(Boolean).join(", ") || "—"} />
          {d.nameHistory?.length ? <Row k="Formerly" v={d.nameHistory.join(", ")} /> : null}
          {d.auditor?.current && <Row k="Auditor" v={titleCase(d.auditor.current)} />}
          {d.auditor && d.auditor.changes > 0 && <Row k="Auditor changes" v={`${d.auditor.changes} across ${d.yearsCovered} filed years`} />}
        </dl>
        {d.auditor?.anyAdverse && (
          <p className={`mt-2 rounded-lg px-2.5 py-2 text-xs ring-1 ${d.auditor.adverseRecent || d.auditor.adverseSustained ? "bg-rose-50 text-rose-800 ring-rose-200" : "bg-amber-50 text-amber-800 ring-amber-200"}`}>
            {d.auditor.adverseRecent || d.auditor.adverseSustained ? "⚠" : "•"} Adverse auditor remarks in {d.auditor.adverseYears.join(", ")}
            {!(d.auditor.adverseRecent || d.auditor.adverseSustained) && ` — none since; latest filed year is ${d.auditor.latestFy}.`}
          </p>
        )}
      </Card>
    </div>
  );
}

/* ============================================ PROBE-POWERED SIDE-BY-SIDE COMPARE
   Rendered inside the Compare flow. Lays the enriched suppliers next to each other
   on the full Probe42 dataset — metrics table (best-of-group highlighted), a
   head-to-head trend, and the lever engine per supplier. */
const CMP = ["#0d9488", "#e11d48", "#2563eb", "#f59e0b", "#7c3aed", "#0891b2"];
/** How many of these entities do we hold a Probe42 report for? */
export function enrichedCount(entities: { cin?: string | null }[]): number { return entities.filter((e) => e.cin && DETAILS[e.cin]).length; }

export function ProbeCompare({ entities }: { entities: { cin?: string | null; brand: string }[] }) {
  const cos = entities.map((e) => ({ brand: e.brand, d: e.cin ? DETAILS[e.cin] : undefined })).filter((x): x is { brand: string; d: Detail } => !!x.d);
  const [metric, setMetric] = useState("revenue");
  if (cos.length < 2) return null;
  const col = (i: number) => CMP[i % CMP.length];

  const rows: { label: string; get: (d: Detail) => number | null; fmt: (v: number | null) => string; hi: number }[] = [
    { label: "Revenue", get: (d) => n(d.latest.revenue), fmt: cr, hi: 1 },
    { label: "EBITDA margin", get: (d) => n(d.latest.ebitdaMargin), fmt: pct, hi: 1 },
    { label: "Net margin", get: (d) => n(d.latest.netMargin), fmt: pct, hi: 1 },
    { label: "RoCE", get: (d) => n(d.latest.roce), fmt: pct, hi: 1 },
    { label: "RoE", get: (d) => n(d.latest.roe), fmt: pct, hi: 1 },
    { label: "Debt / equity", get: (d) => n(d.latest.debtEquity), fmt: (v) => (v == null ? "—" : v.toFixed(2)), hi: -1 },
    { label: "Collects (DSO)", get: (d) => n(d.latest.debtorDays), fmt: days, hi: -1 },
    { label: "Pays (DPO)", get: (d) => n(d.latest.payableDays), fmt: days, hi: 0 },
    { label: "Cash cycle", get: (d) => n(d.latest.cashConversion), fmt: days, hi: -1 },
    { label: "Employees", get: (d) => n(d.employees.latest), fmt: (v) => (v == null ? "—" : `${Math.round(v)}`), hi: 1 },
    { label: "Financial score", get: (d) => n(d.score.overall), fmt: (v) => (v == null ? "—" : `${v}/10`), hi: 1 },
  ];
  const bestIdx = (r: (typeof rows)[number]) => {
    if (r.hi === 0) return -1;
    let bi = -1, bv = r.hi === 1 ? -Infinity : Infinity;
    cos.forEach((c, i) => { const v = r.get(c.d); if (v == null) return; if ((r.hi === 1 && v > bv) || (r.hi === -1 && v < bv)) { bv = v; bi = i; } });
    return bi;
  };

  const TM = [
    { key: "revenue", label: "Revenue", unit: (v: number) => `₹${Math.round(v)} Cr`, get: (f: FinRow) => f.revenue },
    { key: "ebitdaMargin", label: "EBITDA margin", unit: (v: number) => `${v}%`, get: (f: FinRow) => f.r.ebitdaMargin },
    { key: "roce", label: "RoCE", unit: (v: number) => `${v}%`, get: (f: FinRow) => f.r.roce },
    { key: "pat", label: "Profit", unit: (v: number) => `₹${Math.round(v)} Cr`, get: (f: FinRow) => f.pat },
  ];
  const tm = TM.find((x) => x.key === metric) ?? TM[0];
  const years = [...new Set(cos.flatMap((c) => c.d.fin.map((f) => f.fy)))].sort();
  const series = cos.map((c, i) => { const m = new Map(c.d.fin.map((f) => [f.fy, tm.get(f)])); return { name: c.brand, color: col(i), points: years.map((y) => m.get(y) ?? null) }; });

  const oppCount = (d: Detail) => d.levers.filter((l) => l.tone === "opportunity").length;
  const cagr = (d: Detail) => { const r = d.fin.map((f) => f.revenue).filter((v): v is number => v != null); return r.length >= 2 && r[0] ? (r[r.length - 1] / r[0]) ** (1 / (r.length - 1)) - 1 : -Infinity; };
  const winBy = (f: (d: Detail) => number) => cos.reduce((b, c) => (f(c.d) > f(b.d) ? c : b), cos[0]);
  const mostRoom = winBy(oppCount), healthiest = winBy((d) => d.score.overall ?? 0), fastest = winBy(cagr);

  return (
    <div className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-3">
        <WinCard emoji="🤝" title="Most negotiation room" name={fullName(mostRoom.d.legalName, mostRoom.brand)} note={`${oppCount(mostRoom.d)} levers in our favour`} />
        <WinCard emoji="🛡️" title="Healthiest" name={fullName(healthiest.d.legalName, healthiest.brand)} note={`Probe score ${healthiest.d.score.overall}/10`} />
        <WinCard emoji="🚀" title="Fastest growing" name={fullName(fastest.d.legalName, fastest.brand)} note={cagr(fastest.d) > 0 ? `${Math.round(cagr(fastest.d) * 100)}%/yr revenue` : "—"} />
      </div>
      <Card title="Side by side" sub="latest year · green = best of the group" accent={TEAL}>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[560px] border-collapse text-sm">
            <thead><tr className="border-b border-slate-200 text-left"><th className="px-3 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">Metric</th>{cos.map((c, i) => <th key={i} className="px-3 py-2 text-right" title={fullName(c.d.legalName, c.brand)}><span className="inline-flex items-center gap-1.5 font-semibold text-slate-800"><span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: col(i) }} />{c.brand}</span></th>)}</tr></thead>
            <tbody>
              {rows.map((r) => { const bi = bestIdx(r); return (
                <tr key={r.label} className="border-t border-slate-100">
                  <td className="px-3 py-1.5 font-medium text-slate-600">{r.label}</td>
                  {cos.map((c, i) => <td key={i} className={`px-3 py-1.5 text-right font-mono tabular-nums ${i === bi ? "rounded bg-emerald-50 font-bold text-emerald-700" : "text-slate-800"}`}>{r.fmt(r.get(c.d))}</td>)}
                </tr>
              ); })}
            </tbody>
          </table>
        </div>
      </Card>
      <Card title="Head-to-head trend" sub="every supplier on one chart" accent={C.indigo}>
        <div className="mb-3 flex flex-wrap gap-1.5">
          {TM.map((x) => <button key={x.key} onClick={() => setMetric(x.key)} className={`rounded-lg px-2.5 py-1 text-xs font-semibold transition ${metric === x.key ? "bg-teal-600 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{x.label}</button>)}
        </div>
        <MultiLine xLabels={years} series={series} valueLabel={tm.unit} height={300} />
      </Card>
      <Card title="Negotiation levers, head to head" sub="what each supplier's numbers hand us" accent={C.amber}>
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
          {cos.map((c, i) => (
            <div key={i} className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
              <div className="mb-1.5 flex items-center gap-1.5 font-semibold text-slate-800" title={fullName(c.d.legalName, c.brand)}><span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: col(i) }} />{c.brand}</div>
              <div className="mb-2 flex flex-wrap gap-1.5 text-xs">
                <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-emerald-700">{c.d.levers.filter((l) => l.tone === "opportunity").length} for us</span>
                <span className="rounded-full bg-amber-100 px-2 py-0.5 text-amber-700">{c.d.levers.filter((l) => l.tone === "watch").length} watch</span>
                <span className="rounded-full bg-rose-100 px-2 py-0.5 text-rose-700">{c.d.levers.filter((l) => l.tone === "risk").length} risk</span>
              </div>
              <ul className="space-y-1 text-xs text-slate-600">{c.d.levers.filter((l) => l.tone === "opportunity").slice(0, 3).map((l, j) => <li key={j}>✅ {l.title}</li>)}</ul>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
function WinCard({ emoji, title, name, note }: { emoji: string; title: string; name: string; note: string }) {
  return (
    <div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200">
      <div className="text-xs font-medium uppercase tracking-wide text-slate-500">{emoji} {title}</div>
      <div className="mt-1 text-lg font-bold text-slate-900">{name}</div>
      <div className="text-xs text-slate-500">{note}</div>
    </div>
  );
}

/* ---------------------------------------------------------------- helpers */
function Kpi({ label, value, tone }: { label: string; value: string | number; tone: string }) {
  const c: Record<string, string> = { ink: "text-slate-900", teal: "text-teal-600", indigo: "text-indigo-600", sky: "text-sky-600", amber: "text-amber-600", emerald: "text-emerald-600", rose: "text-rose-600" };
  return (
    <div className="rounded-xl bg-white p-2.5 shadow-sm ring-1 ring-slate-200">
      <div className="text-[10px] font-medium uppercase tracking-wide text-slate-500">{label}</div>
      <div className={`mt-0.5 text-base font-semibold tabular-nums ${c[tone] ?? c.ink}`}>{value}</div>
    </div>
  );
}
function Versus({ label, self, median, unit, higherSelfBetter }: { label: string; self: number | null; median: number | null; unit: string; higherSelfBetter?: boolean }) {
  const max = Math.max(1, Math.abs(self ?? 0), Math.abs(median ?? 0));
  const better = self != null && median != null && (higherSelfBetter ? self >= median : self <= median);
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-xs">
        <span className="text-slate-600">{label}</span>
        <span className={`font-mono font-semibold ${better ? "text-emerald-600" : "text-slate-500"}`}>{self ?? "—"}{unit} <span className="text-slate-400">vs {median ?? "—"}{unit}</span></span>
      </div>
      <div className="relative h-3 rounded-full bg-slate-100">
        <div className={`absolute inset-y-0 rounded-full ${better ? "bg-emerald-500" : "bg-teal-500"}`} style={{ width: `${(Math.abs(self ?? 0) / max) * 100}%` }} />
        <div className="absolute inset-y-0 w-0.5 bg-slate-500" style={{ left: `${(Math.abs(median ?? 0) / max) * 100}%` }} title={`peer median ${median}${unit}`} />
      </div>
    </div>
  );
}
// The label follows the state. A green tick beside "GST filing delay" read as
// "yes, delayed" — the opposite of what it meant.
function Flag({ on, bad, good }: { on: boolean; bad: string; good: string }) {
  return <span className={`rounded-full px-2 py-0.5 text-xs font-medium ring-1 ${on ? "bg-rose-50 text-rose-700 ring-rose-200" : "bg-emerald-50 text-emerald-700 ring-emerald-200"}`}>{on ? `⚠ ${bad}` : `✓ ${good}`}</span>;
}
function Row({ k, v }: { k: string; v: string }) {
  return <div className="flex justify-between gap-4 border-b border-slate-100 pb-1.5"><dt className="text-slate-500">{k}</dt><dd className="text-right text-slate-800">{v}</dd></div>;
}
function Empty({ t }: { t: string }) { return <div className="py-6 text-center text-sm text-slate-400">{t}</div>; }
